import { getConnection } from "../constants/db.connection.js";
import oracledb from "oracledb";

// COMPCODE DROPDOWN DATA

//  PARENT CHART Order Entry

export async function getOrderEntryCount(req, res) {
  const connection = await getConnection(res);
  try {
    const { selectedYear } = req.query;

    const sql = `
SELECT 
    D.FINYR,
    B.COMPCODE,
    COUNT(*) AS COMPLETED
FROM GTNORDERENTRY A
JOIN GTCOMPMAST B 
    ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTFINANCIALYEAR D 
    ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE  D.FINYR = '${selectedYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY 
    D.FINYR,
    B.COMPCODE
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      completed: po[2],
      type: "Internal Order",
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 1. Order Entry Planning Status Chart

export async function getOrderEntryStatus(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    const sql = `
SELECT D.FINYR,B.COMPCODE,'INTERNAL ORDER' TYPENAME,C.BUYERCODE,0 PENDING,COUNT(*) COMPLETED,1 ORD FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE
UNION ALL
SELECT D.FINYR,B.COMPCODE,'FABRIC PROCESS PLAN' TYPENAME,C.BUYERCODE,Z.COMPLETED-COUNT(*) PENDING,COUNT(*) COMPLETED,2 ORD FROM GTFYPPLAN A
JOIN GTNORDERENTRY AA ON A.ORDERNO = AA.GTNORDERENTRYID
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = AA.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
JOIN (
SELECT D.FINYR,B.COMPCODE,'INTERNAL ORDER' TYPENAME,C.BUYERCODE,0 PENDING,COUNT(*) COMPLETED FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE
) Z ON Z.BUYERCODE = C.BUYERCODE
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}'  AND AA.ORDERTYPE = 'ORDER' AND A.TRANSTYPE = 'PLANNING'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,Z.COMPLETED
UNION ALL
SELECT D.FINYR,B.COMPCODE,'ACCESSORIES PLAN' TYPENAME,C.BUYERCODE,Z.COMPLETED-COUNT(*) PENDING,COUNT(*) COMPLETED,3 ORD FROM GTACCPLAN A
JOIN GTNORDERENTRY AA ON A.ORDERNO = AA.GTNORDERENTRYID
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = AA.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
JOIN (
SELECT D.FINYR,B.COMPCODE,'INTERNAL ORDER' TYPENAME,C.BUYERCODE,0 PENDING,COUNT(*) COMPLETED FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE
) Z ON Z.BUYERCODE = C.BUYERCODE
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}'  AND AA.ORDERTYPE = 'ORDER' AND A.TRANSTYPE = 'PLANNING'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,Z.COMPLETED
UNION ALL
SELECT D.FINYR,B.COMPCODE,'CMT PLAN' TYPENAME,C.BUYERCODE,Z.COMPLETED-COUNT(*) PENDING,COUNT(*) COMPLETED,4 ORD FROM GTCMTPLAN A
JOIN GTNORDERENTRY AA ON A.ORDERNO = AA.GTNORDERENTRYID
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = AA.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
JOIN (
SELECT D.FINYR,B.COMPCODE,'INTERNAL ORDER' TYPENAME,C.BUYERCODE,0 PENDING,COUNT(*) COMPLETED FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE
) Z ON Z.BUYERCODE = C.BUYERCODE
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}'  AND AA.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,Z.COMPLETED
UNION ALL
SELECT D.FINYR,B.COMPCODE,'PRE - BUDGET' TYPENAME,C.BUYERCODE,Z.COMPLETED-COUNT(*) PENDING,COUNT(*) COMPLETED,5 ORD FROM GTBM A
JOIN GTNORDERENTRY AA ON A.ORDERNO = AA.GTNORDERENTRYID
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = AA.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
JOIN (
SELECT D.FINYR,B.COMPCODE,'INTERNAL ORDER' TYPENAME,C.BUYERCODE,0 PENDING,COUNT(*) COMPLETED FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE
) Z ON Z.BUYERCODE = C.BUYERCODE
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND AA.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,Z.COMPLETED
ORDER BY 1,2,4,ORD
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      typeName: po[2],
      buyerCode: po[3],
      pending: po[4],
      completed: po[5],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 2. Order Entry — Buyer Wise Status Chart

export async function getOrderEntryBuyerStatus(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    // SELECT D.FINYR,B.COMPCODE,C.BUYERCODE,NVL(A.SC,'Running') STA,COUNT(*) CNT FROM GTNORDERENTRY A
    // JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
    // JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
    // JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
    // WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}'
    // GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,A.SC
    // ORDER BY 1,2,3,4

    const sql = `

SELECT D.FINYR,B.COMPCODE,C.BUYERCODE,
CASE WHEN ZA.ORDERNO IS NULL THEN NVL(A.SC,'Running') ELSE 'Completed' END STA,COUNT(*) CNT FROM GTNORDERENTRY A 
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
LEFT JOIN (SELECT DISTINCT ZA.ORDERNO FROM GTPRODPENTRY ZA) ZA ON A.GTNORDERENTRYID = ZA.ORDERNO
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND  A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,C.BUYERCODE,A.SC,ZA.ORDERNO
ORDER BY 1,2,3,4
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      buyerCode: po[2],
      status: po[3],
      count: po[4],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 3. Order Entry — Buyer Wise Quantity Chart

export async function getOrderEntryBuyerQtyWise(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    const sql = `

SELECT 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE,
SUM(CASE 
        WHEN ZA.ORDERNO IS NULL THEN NVL(OAD.SHIPQTY, 0)
        ELSE 0 
    END) AS RUNNING_QTY,
SUM(CASE 
        WHEN ZA.ORDERNO IS NOT NULL THEN NVL(OAD.SHIPQTY, 0)
        ELSE 0 
    END) AS COMPLETED_QTY
FROM GTNORDERENTRY A
JOIN ORDERALLOWDET OAD 
    ON OAD.GTNORDERENTRYID = A.GTNORDERENTRYID   
JOIN GTCOMPMAST B 
    ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C 
    ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D 
    ON D.GTFINANCIALYEARID = A.FINYEAR
LEFT JOIN (
    SELECT ORDERNO
    FROM GTPRODPENTRY
    GROUP BY ORDERNO
) ZA 
    ON A.GTNORDERENTRYID = ZA.ORDERNO
WHERE 
    B.COMPCODE = '${companyName}' 
    AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER' AND OAD.TYPENAME<>'SAMPLE'
GROUP BY 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE
ORDER BY 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      buyerCode: po[2],
      runningQty: po[3],
      completedQty: po[4],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 4. Order Entry — Buyer Po No Wise Quantity Chart

export async function getOrderEntryBuyerWisePoNoQty(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    const sql = `
 SELECT 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE,
    OAD.BPONO,
    SUM(NVL(OAD.SHIPQTY, 0)) AS TOTAL_QTY
FROM GTNORDERENTRY A
JOIN ORDERALLOWDET OAD 
    ON OAD.GTNORDERENTRYID = A.GTNORDERENTRYID   
JOIN GTCOMPMAST B 
    ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C 
    ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D 
    ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE 
    B.COMPCODE = '${companyName}'
    AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE,
    OAD.BPONO
ORDER BY 
    D.FINYR,
    B.COMPCODE,
    C.BUYERCODE,
    OAD.BPONO
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      buyerCode: po[2],
      bpono: po[3],
      totalQty: po[4],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 5. Style Item Group Wise Quantity Chart

export async function getOrderEntryStyleWisePoNoQty(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    const sql = `
SELECT D.FINYR,B.COMPCODE,C.BUYERCODE,Z.STYLEGROUP,Z.STYLESUBGROUP,OAD.STYLEITEM,SUM(NVL(OAD.SHIPQTY, 0)) AS TOTAL_QTY
FROM GTNORDERENTRY A 
JOIN ORDERALLOWDET OAD ON OAD.GTNORDERENTRYID = A.GTNORDERENTRYID   
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
JOIN (
SELECT A.STYLEITEM,B.STYLEGROUP,C.STYLESUBGROUP FROM GTSTYLEITEMMAST A
JOIN GTSTYLEGROUPMAST B ON A.STYLEGROUP = B.GTSTYLEGROUPMASTID
JOIN GTSTYLESUBGROUPMAST C ON C.GTSTYLESUBGROUPMASTID = A.STYLESUBGROUP
) Z ON Z.STYLEITEM = OAD.STYLEITEM
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,OAD.STYLEITEM,C.BUYERCODE,Z.STYLEGROUP,Z.STYLESUBGROUP
ORDER BY D.FINYR,B.COMPCODE,BUYERCODE,STYLEGROUP,STYLESUBGROUP,STYLEITEM
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      buyerCode: po[2],
      styleGroup: po[3],
      styleSubGroup: po[4],
      styleItem: po[5],
      totalQty: po[6],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 6. Order Entry — Color Wise Quantity Chart

export async function getOrderEntryColorWiseQty(req, res) {
  const connection = await getConnection(res);
  try {
    const { finYear, companyName } = req.query;

    const sql = `
SELECT D.FINYR,B.COMPCODE,C.BUYERCODE,OAD.COLOR,SUM(NVL(OAD.SHIPQTY, 0)) AS TOTAL_QTY
FROM GTNORDERENTRY A 
JOIN ORDERALLOWDET OAD ON OAD.GTNORDERENTRYID = A.GTNORDERENTRYID   
JOIN GTCOMPMAST B ON A.COMPCODE = B.GTCOMPMASTID
JOIN GTBUYERMAST C ON C.GTBUYERMASTID = A.BUYER
JOIN GTFINANCIALYEAR D ON D.GTFINANCIALYEARID = A.FINYEAR
WHERE B.COMPCODE = '${companyName}' AND D.FINYR = '${finYear}' AND A.ORDERTYPE = 'ORDER'
GROUP BY D.FINYR,B.COMPCODE,OAD.COLOR,C.BUYERCODE
ORDER BY D.FINYR,B.COMPCODE,BUYERCODE,COLOR
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      finYear: po[0],
      compCode: po[1],
      buyerCode: po[2],
      color: po[3],
      totalQty: po[4],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

// 7. Profit and Loss Report Order Dropdown

export async function getOrderEntryProfitLossdropdown(req, res) {
  const connection = await getConnection(res);
  try {
    const { companyName } = req.query;

    const sql = `
SELECT A.ORDERNO
FROM GTACTCOMM A
JOIN GTNORDERENTRY B ON B.ORDERNO = A.ORDERNO
ORDER BY 1 DESC
     `;

    const result = await connection.execute(sql);
    let resp = result.rows?.map((po) => ({
      orderNo: po[0],
    }));
    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving data:", err);
    res.status(500).json({ error: "Internal Server Error" });
  } finally {
    await connection.close();
  }
}

//7. Profit and Loss Report Table

export async function getOrderEntryProfitLossReport(req, res) {
  const connection = await getConnection(res);

  try {
    const { orderNo } = req.query;

    const result = await connection.execute(
      `
SELECT ORDERNO,PROCESSNAME,ROUND((PLANQTY),2)PLANNEDQTY,ROUND((ACTUALQTY),2)ACTUALQTY
FROM(
SELECT DISTINCT ORDERNO,'SALES VALUE'PROCESSNAME,PSALVAL PLANQTY,ASALVAL ACTUALQTY,PLSPP PLANPCS,ACSPP ACTUALPCS,ACSPP-PLSPP DIFF,99 SNO,4 ORD FROM(
SELECT ORDERNO,STYLENAME,PSALVAL,ASALVAL,(PSALVAL/ORDQTY) PLSPP,(ASALVAL/ORDQTY) ACSPP,ORDQTY,SHIPQTY FROM (
SELECT C.ORDERNO,B.STYLEGROUP STYLENAME,(A.ORDERQTY*A.BPRICEPLAN*A.CONVERRATE)-
NVL((SELECT BB.PREBUDEXP ACTUALQTY
FROM GTACTCOMM AA,GTACTCOMMDET BB,GTNORDERENTRY CC
WHERE AA.GTACTCOMMID = BB.GTACTCOMMID
AND AA.ORDERNO = CC.ORDERNO
AND CC.ORDERNO = :ORDERNO
AND BB.PROCESSNAME = 'DISCOUNT' AND CC.ORDERNO=C.ORDERNO),0) PSALVAL,(A.SHIPQTY*A.BPRICEACT*A.ACTULCONVRATE)-
NVL((SELECT BB.ACTUALEXP ACTUALQTY
FROM GTACTCOMM AA,GTACTCOMMDET BB,GTNORDERENTRY CC
WHERE AA.GTACTCOMMID = BB.GTACTCOMMID
AND AA.ORDERNO = CC.ORDERNO
AND CC.ORDERNO = :ORDERNO
AND BB.PROCESSNAME = 'DISCOUNT' AND CC.ORDERNO=C.ORDERNO),0) ASALVAL,A.ORDERQTY ORDQTY,A.SHIPQTY
FROM GTACTCOMM A,GTSTYLEGROUPMAST B,GTNORDERENTRY C
WHERE B.STYLEGROUP = A.STYLEGROUP AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
)
)
UNION ALL
SELECT ORDERNO,'PROFIT'PROCESSNAME,PSALVAL,ASALVAL,PLPPP,ACPPP,ACPPP-PLPPP DIFF,99 SNO,6 ORD FROM (
SELECT ORDERNO,PSALVAL,ASALVAL,PSALVAL/ORDQTY PLPPP,ASALVAL/SHIPQTY ACPPP FROM (
SELECT ORDERNO,SUM(PSALVAL) PSALVAL,SUM(ASALVAL) ASALVAL,SUM(ORDQTY) ORDQTY,SUM(SHIPQTY) SHIPQTY FROM (
SELECT C.ORDERNO,(0-B.PREBUDEXP) PSALVAL, (0-B.ACTUALEXP) ASALVAL,0 ORDQTY,0 SHIPQTY
FROM GTACTCOMM A,GTACTCOMMDET B,GTNORDERENTRY C
WHERE A.GTACTCOMMID = B.GTACTCOMMID  AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
UNION ALL
SELECT ORDERNO,(PSALVAL) PSALVAL,(ASALVAL) ASALVAL,ORDQTY,SHIPQTY FROM (
SELECT DISTINCT C.ORDERNO,B.STYLEGROUP STYLENAME,(A.ORDERQTY*A.BPRICEPLAN*A.CONVERRATE) PSALVAL,(A.SHIPQTY*A.BPRICEACT*A.ACTULCONVRATE) ASALVAL,A.ORDERQTY ORDQTY ,A.SHIPQTY
FROM GTACTCOMM A,GTSTYLEGROUPMAST B,GTNORDERENTRY C
WHERE B.STYLEGROUP = A.STYLEGROUP AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
))
GROUP BY ORDERNO
))
UNION ALL
SELECT ORDERNO,TITLE PROCESSNAME,PSALVAL,ASALVAL,0 PLPPP,0 ACPPP,DIFF,99 SNO,7 ORD FROM (
SELECT ORDERNO,ROUND((PSALVAL),2)PSALVAL,ROUND((ASALVAL),2)ASALVAL,ROUND((CASE WHEN ASALVAL < 0 THEN (0- ((0 - ASALVAL)-PSALVAL)) ELSE ASALVAL-PSALVAL END),2) DIFF,ROUND((ASALVAL-PSALVAL),2) DIFF1,
CASE WHEN ASALVAL > 0 THEN 'PROFIT %' ELSE 'LOSS %' END TITLE FROM
( SELECT x.ORDERNO,X.PSALVAL/Y.PSALVAL*100 PSALVAL,X.ASALVAL/Y.ASALVAL*100 ASALVAL  FROM (
SELECT 1 ORD,ORDERNO,PSALVAL,ASALVAL FROM (
SELECT ORDERNO,SUM(PSALVAL) PSALVAL,SUM(ASALVAL) ASALVAL,SUM(ORDQTY) ORDQTY FROM (
SELECT C.ORDERNO,(0-B.PREBUDEXP) PSALVAL, (0-B.ACTUALEXP) ASALVAL,0 ORDQTY FROM GTACTCOMM A,GTACTCOMMDET B,GTNORDERENTRY C
WHERE A.GTACTCOMMID = B.GTACTCOMMID  AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
UNION ALL
SELECT ORDERNO,(PSALVAL) PSALVAL,(ASALVAL) ASALVAL,ORDQTY FROM (
SELECT DISTINCT C.ORDERNO,B.STYLEGROUP STYLENAME,(A.ORDERQTY*A.BPRICEPLAN*A.CONVERRATE) PSALVAL,(A.SHIPQTY*A.BPRICEACT*A.ACTULCONVRATE) ASALVAL,A.ORDERQTY ORDQTY
FROM GTACTCOMM A,GTSTYLEGROUPMAST B,GTNORDERENTRY C
WHERE B.STYLEGROUP = A.STYLEGROUP AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
)
)GROUP BY ORDERNO
)) X,
(SELECT 1 ORD,ORDERNO,PSALVAL,ASALVAL FROM (
SELECT DISTINCT C.ORDERNO, B.STYLEGROUP STYLENAME,(A.ORDERQTY*A.BPRICEPLAN*A.CONVERRATE)-
NVL((SELECT BB.PREBUDEXP ACTUALQTY
FROM GTACTCOMM AA,GTACTCOMMDET BB,GTNORDERENTRY CC
WHERE AA.GTACTCOMMID = BB.GTACTCOMMID
AND AA.ORDERNO = CC.ORDERNO
AND CC.ORDERNO = :ORDERNO
AND BB.PROCESSNAME = 'DISCOUNT' AND CC.ORDERNO=C.ORDERNO),0) PSALVAL,(A.SHIPQTY*A.BPRICEACT*A.ACTULCONVRATE)-
NVL((SELECT BB.ACTUALEXP ACTUALQTY
FROM GTACTCOMM AA,GTACTCOMMDET BB,GTNORDERENTRY CC
WHERE AA.GTACTCOMMID = BB.GTACTCOMMID
AND AA.ORDERNO = CC.ORDERNO
AND CC.ORDERNO = :ORDERNO
AND BB.PROCESSNAME = 'DISCOUNT' AND CC.ORDERNO=C.ORDERNO),0) ASALVAL,A.ORDERQTY ORDQTY
FROM GTACTCOMM A,GTSTYLEGROUPMAST B,GTNORDERENTRY C
WHERE B.STYLEGROUP = A.STYLEGROUP AND A.ORDERNO = C.ORDERNO AND C.ORDERNO = :ORDERNO
)) Y
WHERE X.ORD = Y.ORD
)
)
ORDER BY 9,8
)
      `,
      { ORDERNO: orderNo },
      {
        outFormat: oracledb.OUT_FORMAT_OBJECT,
      },
    );

    return res.json({
      statusCode: 0,
      data: result.rows || [],
    });
  } catch (err) {
    console.error("Error retrieving data:", err);

    return res.status(500).json({
      statusCode: 1,
      error: err.message,
    });
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}
