import { getConnection } from "../constants/db.connection.js";

export async function getProductionTable(req, res) {
  const connection = await getConnection(res);

  try {
    const {
      compCode,
      fromDate,
      toDate,
      processName = "ALL",
      storeId = "ALL",
    } = req.query;

    const sql = `
SELECT 'CUTTING' PROCESSNAME,DD.COMPCODE,AB.LOCID STOREID,AA.DOCDATE,AB.TP QTY,FF.ORDERNO,
       CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,
       GG.BUYERCODE,GG.BUYERNAME,CC.COLORNAME
FROM CTPRODUCTION AA
JOIN CTPRODDET AB ON AA.CTPRODUCTIONID=AB.CTPRODUCTIONID
JOIN GTCOLORMAST CC ON CC.GTCOLORMASTID=AB.COLOR
JOIN GTCOMPMAST DD ON DD.GTCOMPMASTID=AA.COMPCODE
JOIN GTLOCMAST EE ON EE.GTLOCMASTID=AA.CPSTOREID
JOIN GTNORDERENTRY FF ON FF.ORDERNO=AA.FILENO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE DD.COMPCODE=:COMPCODE1
AND AA.DOCDATE BETWEEN TO_DATE(:FROMDATE1,'YYYY-MM-DD') AND TO_DATE(:TODATE1,'YYYY-MM-DD')
AND AA.RIB='NO'
AND (:PROCESSNAME1='ALL' OR UPPER('CUTTING')=UPPER(:PROCESSNAME1))
AND (:STOREID1='ALL' OR UPPER(TRIM(AB.LOCID))=UPPER(TRIM(:STOREID1)))

UNION ALL

SELECT E.PROCESSNAME,C.COMPCODE,A.LOCID STOREID,A.PEDATE DOCDATE,CC.DAILYPROD QTY,FF.ORDERNO,
       CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,
       GG.BUYERCODE,GG.BUYERNAME,D.COLORNAME
FROM GTGINPROD A
JOIN GTGINPRODDET B ON A.GTGINPRODID=B.GTGINPRODID
JOIN GTGINPRODSUBDET CC ON CC.GTGINPRODID=A.GTGINPRODID AND CC.GTGINPRODID=B.GTGINPRODID AND CC.GTGINPRODDETID=B.GTGINPRODDETID
JOIN GTCOMPMAST C ON C.GTCOMPMASTID=A.COMPCODE
JOIN GTCOLORMAST D ON D.GTCOLORMASTID=B.COLOR
JOIN GTPROCESSMAST E ON E.GTPROCESSMASTID=A.DEPARTMENT
JOIN GTNORDERENTRY FF ON FF.ORDERNO=B.ORDERNO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE C.COMPCODE=:COMPCODE2
AND A.PEDATE BETWEEN TO_DATE(:FROMDATE2,'YYYY-MM-DD') AND TO_DATE(:TODATE2,'YYYY-MM-DD')
AND (:PROCESSNAME2='ALL' OR UPPER(E.PROCESSNAME)=UPPER(:PROCESSNAME2))
AND (:STOREID2='ALL' OR UPPER(TRIM(A.LOCID))=UPPER(TRIM(:STOREID2)))
`;

    const binds = {
      COMPCODE1: compCode,
      FROMDATE1: fromDate,
      TODATE1: toDate,
      PROCESSNAME1: processName,
      STOREID1: storeId,

      COMPCODE2: compCode,
      FROMDATE2: fromDate,
      TODATE2: toDate,
      PROCESSNAME2: processName,
      STOREID2: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        COMPCODE: row[1],
        STOREID: row[2],
        DOCDATE: row[3],
        QTY: row[4],
        ORDERNO: row[5],
        STYLEREFNO: row[6],
        BUYERCODE: row[7],
        BUYERNAME: row[8],
        COLORNAME: row[9],
      })) || [];

    return res.json({
      statusCode: 0,
      data: resp,
    });
  } catch (err) {
    console.error("Error retrieving production data:", err);
    return res.status(500).json({
      statusCode: 1,
      error: err.message,
    });
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}
