import oracledb from "oracledb";
import { getConnection } from "../constants/db.connection.js";

export async function getProductionTable(req, res) {
  const connection = await getConnection(res);

  try {
    const {
      compCode,
      fromDate,
      toDate,
      processName = "ALL",
      storeId = "ALL",
    } = req.query;

    const sql = `
SELECT 'CUTTING' PROCESSNAME,DD.COMPCODE,AB.LOCID STOREID,AA.DOCDATE,AB.TP QTY,FF.ORDERNO,CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,GG.BUYERCODE,GG.BUYERNAME,CC.COLORNAME
FROM CTPRODUCTION AA
JOIN CTPRODDET AB ON AA.CTPRODUCTIONID=AB.CTPRODUCTIONID
JOIN GTCOLORMAST CC ON CC.GTCOLORMASTID=AB.COLOR
JOIN GTCOMPMAST DD ON DD.GTCOMPMASTID=AA.COMPCODE
JOIN GTLOCMAST EE ON EE.GTLOCMASTID=AA.CPSTOREID
JOIN GTNORDERENTRY FF ON FF.ORDERNO=AA.FILENO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE DD.COMPCODE=:COMPCODE
AND AA.DOCDATE BETWEEN :FROMDATE AND :TODATE
AND AA.RIB='NO'
AND (:PROCESSNAME='ALL' OR UPPER('CUTTING')=UPPER(:PROCESSNAME))
AND (:STOREID='ALL' OR UPPER(TRIM(AB.LOCID))=UPPER(TRIM(:STOREID)))
UNION ALL
SELECT E.PROCESSNAME,C.COMPCODE,A.LOCID STOREID,A.PEDATE DOCDATE,CC.DAILYPROD QTY,FF.ORDERNO,CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,GG.BUYERCODE,GG.BUYERNAME,D.COLORNAME
FROM GTGINPROD A
JOIN GTGINPRODDET B ON A.GTGINPRODID=B.GTGINPRODID
JOIN GTGINPRODSUBDET CC ON CC.GTGINPRODID=A.GTGINPRODID AND CC.GTGINPRODID=B.GTGINPRODID AND CC.GTGINPRODDETID=B.GTGINPRODDETID
JOIN GTCOMPMAST C ON C.GTCOMPMASTID=A.COMPCODE
JOIN GTCOLORMAST D ON D.GTCOLORMASTID=B.COLOR
JOIN GTPROCESSMAST E ON E.GTPROCESSMASTID=A.DEPARTMENT
JOIN GTNORDERENTRY FF ON FF.ORDERNO=B.ORDERNO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE C.COMPCODE=:COMPCODE
AND A.PEDATE BETWEEN :FROMDATE AND :TODATE
AND (:PROCESSNAME='ALL' OR UPPER(E.PROCESSNAME)=UPPER(:PROCESSNAME))
AND (:STOREID='ALL' OR UPPER(TRIM(A.LOCID))=UPPER(TRIM(:STOREID)))
`;

    const binds = {
      FROMDATE: fromDate,
      TODATE: toDate,
      COMPCODE: compCode,
      PROCESSNAME: processName,
      STOREID: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        COMPCODE: row[1],
        STOREID: row[2],
        DOCDATE: row[3],
        QTY: row[4],
        ORDERNO: row[5],
        STYLEREFNO: row[6],
        BUYERCODE: row[7],
        BUYERNAME: row[8],
        COLORNAME: row[9],
      })) || [];

    return res.json({
      statusCode: 0,
      data: resp,
    });
  } catch (err) {
    console.error("Error retrieving production data:", err);

    return res.status(500).json({
      statusCode: 1,
      error: err.message,
    });
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}
