import { getConnection } from "../constants/db.connection.js";

export async function getProductionTable(req, res) {
  const connection = await getConnection(res);

  try {
    const {
      compCode,
      fromDate,
      toDate,
      processName = "ALL",
      storeId = "ALL",
    } = req.query;

    const sql = `
SELECT 'CUTTING' PROCESSNAME,DD.COMPCODE,AB.LOCID STOREID,AA.DOCDATE,AB.TP QTY,FF.ORDERNO,
       CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,
       GG.BUYERCODE,GG.BUYERNAME,CC.COLORNAME
FROM CTPRODUCTION AA
JOIN CTPRODDET AB ON AA.CTPRODUCTIONID=AB.CTPRODUCTIONID
JOIN GTCOLORMAST CC ON CC.GTCOLORMASTID=AB.COLOR
JOIN GTCOMPMAST DD ON DD.GTCOMPMASTID=AA.COMPCODE
JOIN GTLOCMAST EE ON EE.GTLOCMASTID=AA.CPSTOREID
JOIN GTNORDERENTRY FF ON FF.ORDERNO=AA.FILENO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE DD.COMPCODE=:COMPCODE1
AND AA.DOCDATE BETWEEN TO_DATE(:FROMDATE1,'YYYY-MM-DD') AND TO_DATE(:TODATE1,'YYYY-MM-DD')
AND AA.RIB='NO'
AND (:PROCESSNAME1='ALL' OR UPPER('CUTTING')=UPPER(:PROCESSNAME1))
AND (:STOREID1='ALL' OR UPPER(TRIM(AB.LOCID))=UPPER(TRIM(:STOREID1)))

UNION ALL

SELECT E.PROCESSNAME,C.COMPCODE,A.LOCID STOREID,A.PEDATE DOCDATE,CC.DAILYPROD QTY,FF.ORDERNO,
       CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END STYLEREFNO,
       GG.BUYERCODE,GG.BUYERNAME,D.COLORNAME
FROM GTGINPROD A
JOIN GTGINPRODDET B ON A.GTGINPRODID=B.GTGINPRODID
JOIN GTGINPRODSUBDET CC ON CC.GTGINPRODID=A.GTGINPRODID AND CC.GTGINPRODID=B.GTGINPRODID AND CC.GTGINPRODDETID=B.GTGINPRODDETID
JOIN GTCOMPMAST C ON C.GTCOMPMASTID=A.COMPCODE
JOIN GTCOLORMAST D ON D.GTCOLORMASTID=B.COLOR
JOIN GTPROCESSMAST E ON E.GTPROCESSMASTID=A.DEPARTMENT
JOIN GTNORDERENTRY FF ON FF.ORDERNO=B.ORDERNO
JOIN GTBUYERMAST GG ON GG.GTBUYERMASTID=FF.BUYER
WHERE C.COMPCODE=:COMPCODE2
AND A.PEDATE BETWEEN TO_DATE(:FROMDATE2,'YYYY-MM-DD') AND TO_DATE(:TODATE2,'YYYY-MM-DD')
AND (:PROCESSNAME2='ALL' OR UPPER(E.PROCESSNAME)=UPPER(:PROCESSNAME2))
AND (:STOREID2='ALL' OR UPPER(TRIM(A.LOCID))=UPPER(TRIM(:STOREID2)))
`;

    const binds = {
      COMPCODE1: compCode,
      FROMDATE1: fromDate,
      TODATE1: toDate,
      PROCESSNAME1: processName,
      STOREID1: storeId,

      COMPCODE2: compCode,
      FROMDATE2: fromDate,
      TODATE2: toDate,
      PROCESSNAME2: processName,
      STOREID2: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        COMPCODE: row[1],
        STOREID: row[2],
        DOCDATE: row[3],
        QTY: row[4],
        ORDERNO: row[5],
        STYLEREFNO: row[6],
        BUYERCODE: row[7],
        BUYERNAME: row[8],
        COLORNAME: row[9],
      })) || [];

    return res.json({
      statusCode: 0,
      data: resp,
    });
  } catch (err) {
    console.error("Error retrieving production data:", err);
    return res.status(500).json({
      statusCode: 1,
      error: err.message,
    });
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

// export async function getProductionSummaryTable(req, res) {
//   const connection = await getConnection(res);

//   try {
//     const { compCode, fromDate, toDate, storeId = "ALL" } = req.query;

//     const sql1 = `
// SELECT
//     src.ORDERNO,
//     src.STYLEREFNO,
//     src.BUYERCODE,
//     src.BUYERNAME,
//     src.COLORNAME,
//     src.COMPCODE,
//     src.STOREID,
//     OQ.ORDERQTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'CUTTING' THEN src.QTY ELSE 0 END) AS CUTTING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'SINGER' THEN src.QTY ELSE 0 END) AS SINGER_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'POWER TABLE' THEN src.QTY ELSE 0 END) AS POWERTABLE_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'IRONING' THEN src.QTY ELSE 0 END) AS IRONING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'SEWING' THEN src.QTY ELSE 0 END) AS SEWING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'CHECKING' THEN src.QTY ELSE 0 END) AS CHECKING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'PACKING' THEN src.QTY ELSE 0 END) AS PACKING_QTY,
//     SUM(src.QTY) AS TOTAL_QTY
// FROM (
//     SELECT
//         'CUTTING' AS PROCESSNAME,
//         DD.COMPCODE,
//         AB.LOCID AS STOREID,
//         AA.DOCDATE,
//         AB.TP AS QTY,
//         FF.ORDERNO,
//         CASE
//             WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO
//             ELSE FF.STYLEREF
//         END AS STYLEREFNO,
//         GG.BUYERCODE,
//         GG.BUYERNAME,
//         CC.COLORNAME
//     FROM CTPRODUCTION AA
//     JOIN CTPRODDET AB
//         ON AA.CTPRODUCTIONID = AB.CTPRODUCTIONID
//     JOIN GTCOLORMAST CC
//         ON CC.GTCOLORMASTID = AB.COLOR
//     JOIN GTCOMPMAST DD
//         ON DD.GTCOMPMASTID = AA.COMPCODE
//     JOIN GTLOCMAST EE
//         ON EE.GTLOCMASTID = AA.CPSTOREID
//     JOIN GTNORDERENTRY FF
//         ON FF.ORDERNO = AA.FILENO
//     JOIN GTBUYERMAST GG
//         ON GG.GTBUYERMASTID = FF.BUYER
//     WHERE DD.COMPCODE = :COMPCODE
//         AND AA.DOCDATE BETWEEN :FROMDATE AND :TODATE
//         AND AA.RIB = 'NO'
//         AND (
//             :STOREID = 'ALL'
//             OR UPPER(TRIM(AB.LOCID)) = UPPER(TRIM(:STOREID))
//         )

//     UNION ALL

//     SELECT
//         UPPER(TRIM(E.PROCESSNAME)) AS PROCESSNAME,
//         C.COMPCODE,
//         A.LOCID AS STOREID,
//         A.PEDATE AS DOCDATE,
//         CC.DAILYPROD AS QTY,
//         FF.ORDERNO,
//         CASE
//             WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO
//             ELSE FF.STYLEREF
//         END AS STYLEREFNO,
//         GG.BUYERCODE,
//         GG.BUYERNAME,
//         D.COLORNAME
//     FROM GTGINPROD A
//     JOIN GTGINPRODDET B
//         ON A.GTGINPRODID = B.GTGINPRODID
//     JOIN GTGINPRODSUBDET CC
//         ON CC.GTGINPRODID = B.GTGINPRODID
//         AND CC.GTGINPRODDETID = B.GTGINPRODDETID
//     JOIN GTCOMPMAST C
//         ON C.GTCOMPMASTID = A.COMPCODE
//     JOIN GTCOLORMAST D
//         ON D.GTCOLORMASTID = B.COLOR
//     JOIN GTPROCESSMAST E
//         ON E.GTPROCESSMASTID = A.DEPARTMENT
//     JOIN GTNORDERENTRY FF
//         ON FF.ORDERNO = B.ORDERNO
//     JOIN GTBUYERMAST GG
//         ON GG.GTBUYERMASTID = FF.BUYER
//     WHERE C.COMPCODE = :COMPCODE
//         AND A.PEDATE BETWEEN :FROMDATE AND :TODATE
//         AND (
//             :STOREID = 'ALL'
//             OR UPPER(TRIM(A.LOCID)) = UPPER(TRIM(:STOREID))
//         )
// ) src
// LEFT JOIN (
//     SELECT
//         OD.ORDERNO,
//         SUM(OD.SHIPQTY) AS ORDERQTY
//     FROM ORDERALLOWDET OD
//     GROUP BY OD.ORDERNO
// ) OQ
//     ON OQ.ORDERNO = src.ORDERNO
// GROUP BY
//     src.ORDERNO,
//     src.STYLEREFNO,
//     src.BUYERCODE,
//     src.BUYERNAME,
//     src.COLORNAME,
//     src.COMPCODE,
//     src.STOREID,
//     OQ.ORDERQTY
// ORDER BY
//     src.ORDERNO,
//     src.COLORNAME
// `;

//     const sql = `
// SELECT
//     src.ORDERNO,
//     src.STYLEREFNO,
//     src.BUYERCODE,
//     src.BUYERNAME,
//     src.COLORNAME,
//     src.COMPCODE,
//     src.STOREID,
//     OD_STYLE.STYLEGROUP,
//     OD_STYLE.STYLEITEM,
//     OQ.ORDERQTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'CUTTING'     THEN src.QTY ELSE 0 END) AS CUTTING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'SINGER'      THEN src.QTY ELSE 0 END) AS SINGER_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'POWER TABLE' THEN src.QTY ELSE 0 END) AS POWERTABLE_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'IRONING'     THEN src.QTY ELSE 0 END) AS IRONING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'SEWING'      THEN src.QTY ELSE 0 END) AS SEWING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'CHECKING'    THEN src.QTY ELSE 0 END) AS CHECKING_QTY,
//     SUM(CASE WHEN src.PROCESSNAME = 'PACKING'     THEN src.QTY ELSE 0 END) AS PACKING_QTY,
//     SUM(src.QTY) AS TOTAL_QTY
// FROM (
//     -- CUTTING
//     SELECT
//         'CUTTING' AS PROCESSNAME,
//         DD.COMPCODE,
//         AB.LOCID AS STOREID,
//         AA.DOCDATE,
//         AB.TP AS QTY,
//         FF.ORDERNO,
//         CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END AS STYLEREFNO,
//         GG.BUYERCODE,
//         GG.BUYERNAME,
//         CC.COLORNAME
//     FROM CTPRODUCTION AA
//     JOIN CTPRODDET AB       ON AA.CTPRODUCTIONID = AB.CTPRODUCTIONID
//     JOIN GTCOLORMAST CC     ON CC.GTCOLORMASTID  = AB.COLOR
//     JOIN GTCOMPMAST DD      ON DD.GTCOMPMASTID   = AA.COMPCODE
//     JOIN GTLOCMAST EE       ON EE.GTLOCMASTID    = AA.CPSTOREID
//     JOIN GTNORDERENTRY FF   ON FF.ORDERNO        = AA.FILENO
//     JOIN GTBUYERMAST GG     ON GG.GTBUYERMASTID  = FF.BUYER
//     WHERE DD.COMPCODE = :COMPCODE
//       AND AA.DOCDATE BETWEEN TO_DATE(:FROMDATE, 'YYYY-MM-DD')
//                          AND TO_DATE(:TODATE,   'YYYY-MM-DD')
//       AND AA.RIB = 'NO'
//       AND (:STOREID = 'ALL' OR UPPER(TRIM(AB.LOCID)) = UPPER(TRIM(:STOREID)))

//     UNION ALL

//     -- OTHER PROCESSES
//     SELECT
//         UPPER(TRIM(E.PROCESSNAME)) AS PROCESSNAME,
//         C.COMPCODE,
//         A.LOCID AS STOREID,
//         A.PEDATE AS DOCDATE,
//         CC.DAILYPROD AS QTY,
//         FF.ORDERNO,
//         CASE WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO ELSE FF.STYLEREF END AS STYLEREFNO,
//         GG.BUYERCODE,
//         GG.BUYERNAME,
//         D.COLORNAME
//     FROM GTGINPROD A
//     JOIN GTGINPRODDET B         ON A.GTGINPRODID        = B.GTGINPRODID
//     JOIN GTGINPRODSUBDET CC     ON CC.GTGINPRODID       = B.GTGINPRODID
//                                 AND CC.GTGINPRODDETID   = B.GTGINPRODDETID
//     JOIN GTCOMPMAST C           ON C.GTCOMPMASTID       = A.COMPCODE
//     JOIN GTCOLORMAST D          ON D.GTCOLORMASTID      = B.COLOR
//     JOIN GTPROCESSMAST E        ON E.GTPROCESSMASTID    = A.DEPARTMENT
//     JOIN GTNORDERENTRY FF       ON FF.ORDERNO           = B.ORDERNO
//     JOIN GTBUYERMAST GG         ON GG.GTBUYERMASTID     = FF.BUYER
//     WHERE C.COMPCODE = :COMPCODE
//       AND A.PEDATE BETWEEN TO_DATE(:FROMDATE, 'YYYY-MM-DD')
//                        AND TO_DATE(:TODATE,   'YYYY-MM-DD')
//       AND (:STOREID = 'ALL' OR UPPER(TRIM(A.LOCID)) = UPPER(TRIM(:STOREID)))
// ) src
// -- STYLEGROUP / STYLEITEM fetched safely (one row per ORDERNO) — no row multiplication
// LEFT JOIN (
//     SELECT
//         ORDERNO,
//         MAX(STYLEGROUP) AS STYLEGROUP,
//         MAX(STYLEITEM)  AS STYLEITEM
//     FROM ORDERALLOWDET
//     GROUP BY ORDERNO
// ) OD_STYLE ON OD_STYLE.ORDERNO = src.ORDERNO
// -- ORDER QTY aggregated separately
// LEFT JOIN (
//     SELECT
//         ORDERNO,
//         SUM(SHIPQTY) AS ORDERQTY
//     FROM ORDERALLOWDET
//     GROUP BY ORDERNO
// ) OQ ON OQ.ORDERNO = src.ORDERNO
// GROUP BY
//     src.ORDERNO,
//     src.STYLEREFNO,
//     src.BUYERCODE,
//     src.BUYERNAME,
//     src.COLORNAME,
//     src.COMPCODE,
//     src.STOREID,
//     OD_STYLE.STYLEGROUP,
//     OD_STYLE.STYLEITEM,
//     OQ.ORDERQTY
// ORDER BY
//     src.ORDERNO,
//     src.COLORNAME
// `;

//     const binds = {
//       COMPCODE: compCode,
//       FROMDATE: fromDate,
//       TODATE: toDate,
//       STOREID: storeId,
//     };

//     const result = await connection.execute(sql, binds);

//     const resp =
//       result.rows?.map((row) => ({
//         ORDERNO: row[0],
//         STYLEREFNO: row[1],
//         BUYERCODE: row[2],
//         BUYERNAME: row[3],
//         COLORNAME: row[4],
//         COMPCODE: row[5],
//         STOREID: row[6],
//         STYLEGROUP: row[7],
//         STYLEITEM: row[8],
//         ORDERQTY: row[9],
//         CUTTING_QTY: row[10],
//         SINGER_QTY: row[11],
//         POWERTABLE_QTY: row[12],
//         IRONING_QTY: row[13],
//         SEWING_QTY: row[14],
//         CHECKING_QTY: row[15],
//         PACKING_QTY: row[16],
//         TOTAL_QTY: row[17],
//       })) || [];

//     return res.json({
//       statusCode: 0,
//       data: resp,
//     });
//   } catch (err) {
//     console.error("Error retrieving production summary:", err);

//     return res.status(500).json({
//       statusCode: 1,
//       error: err.message,
//     });
//   } finally {
//     if (connection) {
//       await connection.close();
//     }
//   }
// }
export async function getProductionSummaryTable(req, res) {
  const connection = await getConnection(res);

  try {
    const { compCode, fromDate, toDate, storeId = "ALL" } = req.query;

    const sql = `
SELECT
    src.ORDERNO,
    src.STYLEREFNO,
    src.BUYERCODE,
    src.BUYERNAME,
    src.COLORNAME,
    src.COMPCODE,
    src.STOREID,
    OD_STYLE.STYLEGROUP,
    OD_STYLE.STYLEITEM,
    MAX(src.ORDERQTY)   AS ORDERQTY,
    MAX(src.TOTPRODQTY) AS TOTPRODQTY,
    MAX(src.ORDERUOM)   AS ORDERUOM,
    SUM(CASE WHEN src.PROCESSNAME = 'CUTTING'     THEN src.QTY ELSE 0 END) AS CUTTING_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'SINGER'      THEN src.QTY ELSE 0 END) AS SINGER_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'POWER TABLE' THEN src.QTY ELSE 0 END) AS POWERTABLE_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'IRONING'     THEN src.QTY ELSE 0 END) AS IRONING_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'SEWING'      THEN src.QTY ELSE 0 END) AS SEWING_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'CHECKING'    THEN src.QTY ELSE 0 END) AS CHECKING_QTY,
    SUM(CASE WHEN src.PROCESSNAME = 'PACKING'     THEN src.QTY ELSE 0 END) AS PACKING_QTY,
    SUM(src.QTY) AS TOTAL_QTY
FROM (
    SELECT
        'CUTTING' AS PROCESSNAME,
        DD.COMPCODE,
        AB.LOCID AS STOREID,
        AA.DOCDATE,
        AB.TP AS QTY,
        FF.ORDERNO,
        FF.ORDERQTY,
        FF.TOTPRODQTY,
        FF.ORDERUOM,
        CASE
            WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO
            ELSE FF.STYLEREF
        END AS STYLEREFNO,
        GG.BUYERCODE,
        GG.BUYERNAME,
        CC.COLORNAME
    FROM CTPRODUCTION AA
    JOIN CTPRODDET AB       ON AA.CTPRODUCTIONID = AB.CTPRODUCTIONID
    JOIN GTCOLORMAST CC     ON CC.GTCOLORMASTID  = AB.COLOR
    JOIN GTCOMPMAST DD      ON DD.GTCOMPMASTID   = AA.COMPCODE
    JOIN GTLOCMAST EE       ON EE.GTLOCMASTID    = AA.CPSTOREID
    JOIN GTNORDERENTRY FF   ON FF.ORDERNO        = AA.FILENO
    JOIN GTBUYERMAST GG     ON GG.GTBUYERMASTID  = FF.BUYER
    WHERE DD.COMPCODE = :COMPCODE
      AND AA.DOCDATE BETWEEN TO_DATE(:FROMDATE, 'YYYY-MM-DD')
                         AND TO_DATE(:TODATE,   'YYYY-MM-DD')
      AND AA.RIB = 'NO'
      AND (:STOREID = 'ALL' OR UPPER(TRIM(AB.LOCID)) = UPPER(TRIM(:STOREID)))

    UNION ALL

    SELECT
        UPPER(TRIM(E.PROCESSNAME)) AS PROCESSNAME,
        C.COMPCODE,
        A.LOCID AS STOREID,
        A.PEDATE AS DOCDATE,
        CC.DAILYPROD AS QTY,
        FF.ORDERNO,
        FF.ORDERQTY,
        FF.TOTPRODQTY,
        FF.ORDERUOM,
        CASE
            WHEN FF.STYLEREF IS NULL THEN FF.STYLEREFNO
            ELSE FF.STYLEREF
        END AS STYLEREFNO,
        GG.BUYERCODE,
        GG.BUYERNAME,
        D.COLORNAME
    FROM GTGINPROD A
    JOIN GTGINPRODDET B         ON A.GTGINPRODID      = B.GTGINPRODID
    JOIN GTGINPRODSUBDET CC     ON CC.GTGINPRODID     = B.GTGINPRODID
                                AND CC.GTGINPRODDETID = B.GTGINPRODDETID
    JOIN GTCOMPMAST C           ON C.GTCOMPMASTID     = A.COMPCODE
    JOIN GTCOLORMAST D          ON D.GTCOLORMASTID    = B.COLOR
    JOIN GTPROCESSMAST E        ON E.GTPROCESSMASTID  = A.DEPARTMENT
    JOIN GTNORDERENTRY FF       ON FF.ORDERNO         = B.ORDERNO
    JOIN GTBUYERMAST GG         ON GG.GTBUYERMASTID   = FF.BUYER
    WHERE C.COMPCODE = :COMPCODE
      AND A.PEDATE BETWEEN TO_DATE(:FROMDATE, 'YYYY-MM-DD')
                       AND TO_DATE(:TODATE,   'YYYY-MM-DD')
      AND (:STOREID = 'ALL' OR UPPER(TRIM(A.LOCID)) = UPPER(TRIM(:STOREID)))
) src
LEFT JOIN (
    SELECT
        ORDERNO,
        MAX(STYLEGROUP) AS STYLEGROUP,
        MAX(STYLEITEM)  AS STYLEITEM
    FROM ORDERALLOWDET
    GROUP BY ORDERNO
) OD_STYLE ON OD_STYLE.ORDERNO = src.ORDERNO
GROUP BY
    src.ORDERNO,
    src.STYLEREFNO,
    src.BUYERCODE,
    src.BUYERNAME,
    src.COLORNAME,
    src.COMPCODE,
    src.STOREID,
    OD_STYLE.STYLEGROUP,
    OD_STYLE.STYLEITEM
ORDER BY
    src.ORDERNO,
    src.COLORNAME
`;

    const binds = {
      COMPCODE: compCode,
      FROMDATE: fromDate,
      TODATE: toDate,
      STOREID: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        ORDERNO: row[0],
        STYLEREFNO: row[1],
        BUYERCODE: row[2],
        BUYERNAME: row[3],
        COLORNAME: row[4],
        COMPCODE: row[5],
        STOREID: row[6],
        STYLEGROUP: row[7],
        STYLEITEM: row[8],
        ORDERQTY: row[9],
        TOTPRODQTY: row[10],
        ORDERUOM: row[11],
        CUTTING_QTY: row[12],
        SINGER_QTY: row[13],
        POWERTABLE_QTY: row[14],
        IRONING_QTY: row[15],
        SEWING_QTY: row[16],
        CHECKING_QTY: row[17],
        PACKING_QTY: row[18],
        TOTAL_QTY: row[19],
      })) || [];

    return res.json({
      statusCode: 0,
      data: resp,
    });
  } catch (err) {
    console.error("Error retrieving production summary:", err);

    return res.status(500).json({
      statusCode: 1,
      error: err.message,
    });
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function getProductionEfficiencyTable(req, res) {
  const connection = await getConnection(res);

  try {
    const { compCode, date, processName = "ALL", storeId = "ALL" } = req.query;

    const sql = `
SELECT X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT,
  SUM(X.CUTTING) CUTTING, SUM(X.CHECKING) CHECKING, SUM(X.SINGER) SINGER,
  SUM(X.POWERTABLE) POWERTABLE, SUM(X.SEWING) SEWING
FROM (
  SELECT 'CUTTING' PROCESSNAME, A.FILENO ORDERNO, A.DOCID, A.DOCDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.CPLOCID AS UNIT,
    SUM(B.PRODQTY1) AS CUTTING, 0 CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 1 ORD
  FROM CTPRODUCTION A
  INNER JOIN CTPRODDET B ON A.CTPRODUCTIONID = B.CTPRODUCTIONID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.STYLEITEM
  WHERE A.DOCDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD') AND A.RIB = 'NO'
    AND ('CUTTING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.CPLOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY A.DOCID, A.FILENO, A.DOCDATE, E.STYLEITEM, C.COLORNAME, A.CPLOCID
  UNION ALL
  SELECT 'CHECKING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, SUM(B.PRODQTY) CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 2 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'CHECKING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('CHECKING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SINGER' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, SUM(B.PRODQTY) SINGER, 0 POWERTABLE, 0 SEWING, 3 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SINGER' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SINGER' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'POWER TABLE' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, SUM(B.PRODQTY) POWERTABLE, 0 SEWING, 4 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'POWER TABLE' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('POWER TABLE' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SEWING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, 0 POWERTABLE, SUM(B.PRODQTY) SEWING, 5 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SEWING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SEWING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
) X
GROUP BY X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT, X.ORD
ORDER BY X.ORD, X.DOCID
    `;

    const binds = {
      DOCDATE: date,
      PROCESS: processName,
      LOCID: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        ORDERNO: row[1],
        DOCID: row[2],
        PRODDATE: row[3],
        STYLEITEM: row[4],
        COLORNAME: row[5],
        UNIT: row[6],
        CUTTING: row[7],
        CHECKING: row[8],
        SINGER: row[9],
        POWERTABLE: row[10],
        SEWING: row[11],
      })) || [];

    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving production data:", err);
    return res.status(500).json({ statusCode: 1, error: err.message });
  } finally {
    if (connection) await connection.close();
  }
}

export async function getProductionEfficiencyEmployeeTable(req, res) {
  const connection = await getConnection(res);

  try {
    const { compCode, date, processName = "ALL", storeId = "ALL" } = req.query;

    const sql = `

      SELECT X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT,
  SUM(X.CUTTING) CUTTING, SUM(X.CHECKING) CHECKING, SUM(X.SINGER) SINGER,
  SUM(X.POWERTABLE) POWERTABLE, SUM(X.SEWING) SEWING
FROM (
  SELECT 'CUTTING' PROCESSNAME, A.FILENO ORDERNO, A.DOCID, A.DOCDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.CPLOCID AS UNIT,
    (SELECT SUM(S1.nomanpower) FROM ctprodsizewisedet S1 WHERE A.CTPRODUCTIONID = S1.CTPRODUCTIONID AND B.ctproddetid = S1.ctproddetID) AS CUTTING,
    0 CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 1 ORD
  FROM CTPRODUCTION A
  INNER JOIN CTPRODDET B ON A.CTPRODUCTIONID = B.CTPRODUCTIONID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.STYLEITEM
  WHERE A.DOCDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD') AND A.RIB = 'NO'
    AND ('CUTTING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.CPLOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY A.DOCID, A.FILENO, A.DOCDATE, E.STYLEITEM, C.COLORNAME, A.CPLOCID,A.CTPRODUCTIONID,B.ctproddetid
  UNION ALL
  SELECT 'CHECKING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, SUM(B.nomanpower1) CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 2 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'CHECKING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('CHECKING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SINGER' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, SUM(B.nomanpower1) SINGER, 0 POWERTABLE, 0 SEWING, 3 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SINGER' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SINGER' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'POWER TABLE' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, SUM(B.nomanpower1) POWERTABLE, 0 SEWING, 4 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'POWER TABLE' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('POWER TABLE' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SEWING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, 0 POWERTABLE, SUM(B.nomanpower1) SEWING, 5 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SEWING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SEWING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
) X
GROUP BY X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT, X.ORD
ORDER BY X.ORD, X.DOCID
    `;

    const binds = {
      DOCDATE: date,
      PROCESS: processName,
      LOCID: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        ORDERNO: row[1],
        DOCID: row[2],
        PRODDATE: row[3],
        STYLEITEM: row[4],
        COLORNAME: row[5],
        UNIT: row[6],
        CUTTING: row[7],
        CHECKING: row[8],
        SINGER: row[9],
        POWERTABLE: row[10],
        SEWING: row[11],
      })) || [];

    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving production data:", err);
    return res.status(500).json({ statusCode: 1, error: err.message });
  } finally {
    if (connection) await connection.close();
  }
}

export async function getProductionEfficiencyEffTable(req, res) {
  const connection = await getConnection(res);

  try {
    const { compCode, date, processName = "ALL", storeId = "ALL" } = req.query;

    const sql = `
SELECT X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT,
  AVG(X.CUTTING) CUTTING, AVG(X.CHECKING) CHECKING, AVG(X.SINGER) SINGER,
  AVG(X.POWERTABLE) POWERTABLE, AVG(X.SEWING) SEWING
FROM (
  SELECT 'CUTTING' PROCESSNAME, A.FILENO ORDERNO, A.DOCID, A.DOCDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.CPLOCID AS UNIT,
    (ROUND(DECODE((B.SAM * B.PRODQTY1),0,0,(B.SAM * B.PRODQTY1)/
                 ((SELECT SUM(S1.nomanpower) FROM ctprodsizewisedet S1 WHERE A.CTPRODUCTIONID = S1.CTPRODUCTIONID AND B.ctproddetid = S1.ctproddetID) * 600)),2)) AS CUTTING,
    0 CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 1 ORD
  FROM CTPRODUCTION A
  INNER JOIN CTPRODDET B ON A.CTPRODUCTIONID = B.CTPRODUCTIONID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.STYLEITEM
  WHERE A.DOCDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD') AND A.RIB = 'NO'
    AND ('CUTTING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.CPLOCID = :LOCID OR 'ALL' = :LOCID)
--  GROUP BY A.DOCID, A.FILENO, A.DOCDATE, E.STYLEITEM, C.COLORNAME, A.CPLOCID,A.CTPRODUCTIONID,B.ctproddetid
  UNION ALL
  SELECT 'CHECKING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, ROUND(DECODE((B.SAMVAL1 * B.PRODQTY),0,0,(B.SAMVAL1 * B.PRODQTY)/(B.nomanpower1 * 600)),2) CHECKING, 0 SINGER, 0 POWERTABLE, 0 SEWING, 2 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'CHECKING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('CHECKING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
--  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SINGER' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, ROUND(DECODE((B.SAMVAL1 * B.PRODQTY),0,0,(B.SAMVAL1 * B.PRODQTY)/(B.nomanpower1 * 600)),2) SINGER, 0 POWERTABLE, 0 SEWING, 3 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SINGER' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SINGER' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
--  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'POWER TABLE' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, ROUND(DECODE((B.SAMVAL1 * B.PRODQTY),0,0,(B.SAMVAL1 * B.PRODQTY)/(B.nomanpower1 * 600)),2) POWERTABLE, 0 SEWING, 4 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'POWER TABLE' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('POWER TABLE' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
--  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
  UNION ALL
  SELECT 'SEWING' PROCESSNAME, B.ORDERNO, A.PENO DOCID, A.PEDATE AS PRODDATE,
    E.STYLEITEM, C.COLORNAME AS COLOR, A.LOCID AS UNIT,
    0 CUTTING, 0 CHECKING, 0 SINGER, 0 POWERTABLE, ROUND(DECODE((B.SAMVAL1 * B.PRODQTY),0,0,(B.SAMVAL1 * B.PRODQTY)/(B.nomanpower1 * 600)),2) SEWING, 5 ORD
  FROM GTGINPROD A
  INNER JOIN GTGINPRODDET B ON A.GTGINPRODID = B.GTGINPRODID
  INNER JOIN GTCOLORMAST C ON B.COLOR = C.GTCOLORMASTID
  INNER JOIN GTPROCESSMAST D ON A.DEPARTMENT = D.GTPROCESSMASTID
  INNER JOIN GTSTYLEITEMMAST E ON B.STYLEITEM = E.GTSTYLEITEMMASTID
  WHERE D.PROCESSNAME = 'SEWING' AND A.PEDATE = TO_DATE(:DOCDATE,'YYYY-MM-DD')
    AND ('SEWING' = :PROCESS OR 'ALL' = :PROCESS)
    AND (A.LOCID = :LOCID OR 'ALL' = :LOCID)
--  GROUP BY B.ORDERNO, A.PENO, A.PEDATE, D.PROCESSNAME, B.LINENO1, E.STYLEITEM, C.COLORNAME, A.LOCID
) X
GROUP BY X.PROCESSNAME, X.ORDERNO, X.DOCID, X.PRODDATE, X.STYLEITEM, X.COLOR, X.UNIT, X.ORD
ORDER BY X.ORD, X.DOCID
    `;

    const binds = {
      DOCDATE: date,
      PROCESS: processName,
      LOCID: storeId,
    };

    const result = await connection.execute(sql, binds);

    const resp =
      result.rows?.map((row) => ({
        PROCESSNAME: row[0],
        ORDERNO: row[1],
        DOCID: row[2],
        PRODDATE: row[3],
        STYLEITEM: row[4],
        COLORNAME: row[5],
        UNIT: row[6],
        CUTTING: row[7],
        CHECKING: row[8],
        SINGER: row[9],
        POWERTABLE: row[10],
        SEWING: row[11],
      })) || [];

    return res.json({ statusCode: 0, data: resp });
  } catch (err) {
    console.error("Error retrieving production data:", err);
    return res.status(500).json({ statusCode: 1, error: err.message });
  } finally {
    if (connection) await connection.close();
  }
}
