import { getConnection } from "../constants/db.connection.js";
import oracledb from "oracledb";

// =====================================================================================
// Order Report Queries - SINGLE consolidated function
// Usage: GET /api/order-report?orderNo=XXXX&reportType=YARN_PURCHASE
//
// Valid reportType values:
//   - YARN_PURCHASE
//   - YARN_PURCHASE_TRANSFER
//   - YARN_PROCESS
//   - YARN_PROCESS_TRANSFER
//   - GREY_FABRIC_PURCHASE_PROCESS
//   - GREY_FABRIC_TRANSFER
//   - DYED_FABRIC_PURCHASE_PROCESS
//   - DYED_FABRIC_TRANSFER
//   - ACCESSORY_PURCHASE
//   - ACCESSORY_PURCHASE_TRANSFER
//   - ACCESSORY_PROCESS
//   - ACCESSORY_PROCESS_TRANSFER
//   - CUTTING_MAKING_TRIMMING
//
// Adjust `getConnection` import to match your project structure.
// =====================================================================================

/**
 * Map an oracledb rows array (array-of-arrays) into an array of objects
 * using the supplied field name list (positional).
 */
function mapRows(rows, fields) {
  return (rows || []).map((row) =>
    fields.reduce((obj, field, idx) => {
      obj[field] = row[idx];
      return obj;
    }, {}),
  );
}

// ---------------------------------------------------------------------------
// Report registry: reportType -> { sql, fields }
// Each sql uses a named bind variable :ORDERNO
// ---------------------------------------------------------------------------
const REPORTS = {
  YARN_PURCHASE: {
    sql: `SELECT ORDERNO,PROCESSNAME,YARNNAME||' / '||COLOR DESCRIPTION,UOM,SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,ROUND(SUM(PAMOUNT)/SUM(PQTY),2)) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT,1 AS ORD FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
B.YREQQTY PQTY,B.YRATE PRATE,B.YREQQTY*B.YRATE PAMOUNT,0 AQTY,0 ARATE,0 AAMOUNT
FROM GTBM A,GTBMYARNDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.YPROCESSNAME=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.YCOLOR=F.GTCOLORMASTID AND B.YUOM=G.GTUNITMASTID
AND D.PROCESSNAME IN ('GY PURCHASE','DY PURCHASE')
AND C.ORDERNO=:ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT A.SUPPLIER,B.ORDERNO,D.PROCESSNAME,SUBSTR(B.TRANSTYPE,1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALGRNQTY AQTY ,CASE WHEN H.COMPCODE IN ('AGF','VEL') AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - SPINNING' THEN B.POPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=I.GTYARNPOID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTYARNPODETID) END ARATE,B.TOTALGRNQTY*(CASE WHEN H.COMPCODE IN ('AGF','VEL') AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - SPINNING' THEN B.POPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=I.GTYARNPOID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTYARNPODETID) END ) AAMOUNT
FROM GTYARNPOINWARD A,GTYARNPOINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G,GTCOMPMAST H,GTYARNPO I
WHERE A.GTYARNPOINWARDID=B.GTYARNPOINWARDID AND B.ORDERNO=C.ORDERNO AND B.YARNPROCESS=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.COLORNAME=F.GTCOLORMASTID AND B.UOM=G.GTUNITMASTID AND C.COMPCODE=H.GTCOMPMASTID AND B.PONO=I.GTYARNPOID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='INWARD'
)
GROUP BY PROCESSNAME,YARNNAME,COLOR,UOM,ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,	
0-SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,0-SUM(AAMOUNT) AAMOUNT FROM (
SELECT B.ORDERNO,D.PROCESSNAME,SUBSTR(B.TRANSTYPE,1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.RETQTY AQTY ,CASE WHEN H.COMPCODE='AGF' AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - SPINNING' THEN B.POPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=I.GTYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTYARNPODETID) END ARATE,B.RETQTY*(CASE WHEN H.COMPCODE='AGF' AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - SPINNING' THEN B.POPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=I.GTYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTYARNPODETID) END ) AAMOUNT
FROM GTYARNPOINWARD A,GTYARNPOINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G,GTCOMPMAST H,GTYARNPO I
WHERE A.GTYARNPOINWARDID=B.GTYARNPOINWARDID AND B.ORDERNO=C.ORDERNO AND B.YARNPROCESS=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.COLORNAME=F.GTCOLORMASTID AND B.UOM=G.GTUNITMASTID AND C.COMPCODE=H.GTCOMPMASTID AND B.PONO=I.GTYARNPOID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='RETURN' )
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT B.ORDERNO,D.PROCESSNAME,SUBSTR(B.TRANSTYPE,1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALGRNQTY AQTY ,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDYPBILLENTRY AA,GTDYPBILLENTRYDET BB
WHERE AA.GTDYPBILLENTRYID=BB.GTDYPBILLENTRYID AND BB.PONO=H.GTDYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTDYARNPODETID) ARATE,B.TOTALGRNQTY*(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDYPBILLENTRY AA,GTDYPBILLENTRYDET BB
WHERE AA.GTDYPBILLENTRYID=BB.GTDYPBILLENTRYID AND BB.PONO=H.GTDYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTDYARNPODETID) AAMOUNT
FROM GTDYARNPOINWARD A,GTDYARNPOINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G,GTDYARNPO H
WHERE A.GTDYARNPOINWARDID=B.GTDYARNPOINWARDID AND B.ORDERNO=C.ORDERNO AND B.YARNPROCESS=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.COLORNAME=F.GTCOLORMASTID AND B.UOM=G.GTUNITMASTID AND B.PONO=H.GTDYARNPOID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='INWARD'
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
0-SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,0-SUM(AAMOUNT) AAMOUNT FROM (
SELECT B.ORDERNO,D.PROCESSNAME,SUBSTR(B.TRANSTYPE,1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALGRNQTY AQTY ,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=H.GTDYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTDYARNPODETID) ARATE,B.TOTALGRNQTY*(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGRPBILLENTRY AA,GTGRPBILLENTRYDET BB
WHERE AA.GTGRPBILLENTRYID=BB.GTGRPBILLENTRYID AND BB.PONO=H.GTDYARNPOID AND BB.YARNNAME=E.GTYARNMASTERID AND BB.COLOR=F.GTCOLORMASTID
AND BB.DETAILID=B.GTDYARNPODETID) AAMOUNT
FROM GTDYARNPOINWARD A,GTDYARNPOINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G,GTDYARNPO H
WHERE A.GTDYARNPOINWARDID=B.GTDYARNPOINWARDID AND B.ORDERNO=C.ORDERNO AND B.YARNPROCESS=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.COLORNAME=F.GTCOLORMASTID AND B.UOM=G.GTUNITMASTID AND B.PONO=H.GTDYARNPOID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='RETURN'
)
GROUP BY PROCESSNAME,YARNNAME,COLOR,UOM,ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT A.TOORDNO ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TRAQTY AQTY ,CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END ARATE,B.TRAQTY*
(CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END) AAMOUNT
FROM GTYTRANS A,GTYSTOCKINFODET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTYTRANSID=B.GTYTRANSID AND A.TOORDNO=C.ORDERNO AND B.PROCESSNAME2=D.PROCESSNAME
AND B.YARNNAME1=E.YARNNAME AND B.COLOR1=F.COLORNAME AND B.UOM1=G.UNITNAME
AND C.ORDERNO=:ORDERNO
AND D.PROCESSNAME IN ('GY PURCHASE','DY PURCHASE')
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
)
GROUP BY PROCESSNAME,YARNNAME,COLOR,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  YARN_PURCHASE_TRANSFER: {
    sql: `SELECT ORDERNO,PROCESSNAME,YARNNAME||' / '||COLOR DESCRIPTION,UOM ,SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,ROUND(SUM(PAMOUNT)/SUM(PQTY),2)) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT,1 AS ORD FROM (
SELECT ORDERNO,PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
0-SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,0-SUM(AAMOUNT) AAMOUNT FROM (
SELECT A.FRMORDNO ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TRAQTY AQTY ,CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END ARATE,B.TRAQTY*
(CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END) AAMOUNT
FROM GTYTRANS A,GTYSTOCKINFODET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTYTRANSID=B.GTYTRANSID AND A.FRMORDNO=C.ORDERNO AND B.PROCESSNAME2=D.PROCESSNAME
AND B.YARNNAME1=E.YARNNAME(+) AND B.COLOR1=F.COLORNAME AND B.UOM1=G.UNITNAME
AND C.ORDERNO=:ORDERNO
AND D.PROCESSNAME IN ('GY PURCHASE','DY PURCHASE')
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  YARN_PROCESS: {
    sql: `SELECT ORDERNO,PROCESSNAME,YARNNAME||' / '||COLOR DESCRIPTION,UOM,SUM(PQTY) PQTY,decode(SUM(PAMOUNT),0,0,ROUND(SUM(PAMOUNT)/SUM(PQTY),2)) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT,2 AS ORD FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
B.YGQTY PQTY,B.YRATE PRATE,B.YAMOUNT PAMOUNT,0 AQTY,0 ARATE,0 AAMOUNT
FROM GTBM A,GTBMYARNDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.YPROCESSNAME=D.GTPROCESSMASTID
AND B.YARNNAME=E.GTYARNMASTERID AND B.YCOLOR=F.GTCOLORMASTID AND B.YUOM=G.GTUNITMASTID
AND D.PROCESSNAME NOT IN ('GY PURCHASE','DY PURCHASE')
AND C.ORDERNO=:ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT A.ORDERNO,D.PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALRECQTY+ (B.TOTALRECQTY*(SELECT SUM(BB.LOSSQTY)/SUM(BB.ISSRECQTY)
FROM GTYARNPRORECEIPT AA,GTYARNPRORECEIPTSTOCK BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTYARNMASTER EE,GTCOLORMAST FF,GTUNITMAST GG
WHERE AA.GTYARNPRORECEIPTID=BB.GTYARNPRORECEIPTID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.ALIASNAME1=EE.GTYARNMASTERID AND BB.COLOR1=FF.GTCOLORMASTID AND BB.UOM1=GG.GTUNITMASTID
AND AA.GTYARNPRORECEIPTID=A.GTYARNPRORECEIPTID )) AQTY ,
CASE WHEN H.COMPCODE='FLF' AND A.SUPPLIER='FREELOOK FASHIONS' THEN B.JOBRATE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTYPBILLENTRY AA,GTYPBILLENTRYDET BB
WHERE AA.GTYPBILLENTRYID=BB.GTYPBILLENTRYID AND BB.DETAILID=B.DETAILID) END ARATE,
(B.TOTALRECQTY+(B.TOTALRECQTY*(SELECT SUM(BB.LOSSQTY)/SUM(BB.ISSRECQTY)
FROM GTYARNPRORECEIPT AA,GTYARNPRORECEIPTSTOCK BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTYARNMASTER EE,GTCOLORMAST FF,GTUNITMAST GG
WHERE AA.GTYARNPRORECEIPTID=BB.GTYARNPRORECEIPTID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.ALIASNAME1=EE.GTYARNMASTERID AND BB.COLOR1=FF.GTCOLORMASTID AND BB.UOM1=GG.GTUNITMASTID
AND AA.GTYARNPRORECEIPTID=A.GTYARNPRORECEIPTID )))*(CASE WHEN H.COMPCODE='FLF' AND A.SUPPLIER='FREELOOK FASHIONS' THEN B.JOBRATE ELSE
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTYPBILLENTRY AA,GTYPBILLENTRYDET BB
WHERE AA.GTYPBILLENTRYID=BB.GTYPBILLENTRYID AND BB.DETAILID=B.DETAILID  ) END) AAMOUNT
FROM GTYARNPRORECEIPT A,GTYARNPRORECEIPTDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G,GTCOMPMAST H
WHERE A.GTYARNPRORECEIPTID=B.GTYARNPRORECEIPTID AND A.ORDERNO=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID
AND B.ALIASNAME=E.GTYARNMASTERID AND B.COLOR=F.GTCOLORMASTID AND B.UOM=G.GTUNITMASTID AND C.COMPCODE=H.GTCOMPMASTID
AND C.ORDERNO=:ORDERNO
 )
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
UNION
SELECT ORDERNO,PROCESSNAME,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT A.TOORDNO ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TRAQTY AQTY ,CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END ARATE,B.TRAQTY*
(CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END) AAMOUNT
FROM GTYTRANS A,GTYSTOCKINFODET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTYTRANSID=B.GTYTRANSID AND A.TOORDNO=C.ORDERNO AND B.PROCESSNAME2=D.PROCESSNAME
AND B.YARNNAME1=E.YARNNAME AND B.COLOR1=F.COLORNAME AND B.UOM1=G.UNITNAME
AND C.ORDERNO=:ORDERNO
AND D.PROCESSNAME NOT IN ('GY PURCHASE','DY PURCHASE')
 )
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
)
GROUP BY PROCESSNAME,YARNNAME,COLOR,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  YARN_PROCESS_TRANSFER: {
    sql: `SELECT ORDERNO,PROCESSNAME,YARNNAME||' / '||COLOR DESCRIPTION,UOM,SUM(PQTY) PQTY,
CASE WHEN SUM(PAMOUNT)=0 OR SUM(PQTY)=0 THEN 0 ELSE ROUND(SUM(PAMOUNT)/SUM(PQTY),2) END PRATE,SUM(PAMOUNT) PAMOUNT,
SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT,2 AS ORD FROM (
SELECT ORDERNO,PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,SUM(PQTY) PQTY,SUM(PRATE) PRATE,SUM(PAMOUNT) PAMOUNT,
0-SUM(AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(AQTY),2) ARATE,0-SUM(AAMOUNT) AAMOUNT FROM (
SELECT C.ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.YARNNAME,F.COLORNAME COLOR,G.UNITNAME UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.TRAQTY AQTY ,CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END ARATE,B.TRAQTY*
CASE WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.RATE1
WHEN A.FRMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.RATE1 END AAMOUNT
FROM GTYTRANS A,GTYSTOCKINFODET B,GTNORDERENTRY C,GTPROCESSMAST D,GTYARNMASTER E,GTCOLORMAST F,GTUNITMAST G
WHERE A.GTYTRANSID=B.GTYTRANSID AND A.FRMORDNO=C.ORDERNO AND B.PROCESSNAME2=D.PROCESSNAME
AND B.YARNNAME1=E.YARNNAME AND B.COLOR1=F.COLORNAME AND B.UOM1=G.UNITNAME
AND C.ORDERNO=:ORDERNO
AND D.PROCESSNAME NOT IN ('GY PURCHASE','DY PURCHASE')
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
)
GROUP BY PROCESSNAME,TRANSTYPE,YARNNAME,COLOR,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  GREY_FABRIC_PURCHASE_PROCESS: {
    sql: `SELECT ORDERNO,PROCESSNAME,FABRIC||' / '||COLOR||' / '||DESIGN||' / '||GSM||' / '||GG||' / '||LL||' / '||KDIA||' / '||FDIA DESCRIPTION , UOM ,
SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,SUM(PAMOUNT)/SUM(PQTY)) PRATE,
SUM(PAMOUNT) PAMOUNT,SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,SUM(AAMOUNT)/SUM(AQTY)) ARATE,SUM(AAMOUNT) AAMOUNT,3 AS ORD FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,B.FREQQTY PQTY,B.FRATE PRATE,B.FREQQTY*B.FRATE PAMOUNT,0 AQTY,0 ARATE,0 AAMOUNT
FROM GTBM A,GTFABDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.FPROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.FCOLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND B.FPROCESSNAME=N.PROCESSNAME AND M.PROCESSGROUPNAME='GREY FABRIC'
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT B.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALGRNQTY AQTY,
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGFPBILLENTRY AA,GTGFPBILLENTRYDET BB
WHERE AA.GTGFPBILLENTRYID=BB.GTGFPBILLENTRYID AND BB.DETAILID=B.POID) ARATE,B.TOTALGRNQTY*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGFPBILLENTRY AA,GTGFPBILLENTRYDET BB
WHERE AA.GTGFPBILLENTRYID=BB.GTGFPBILLENTRYID AND BB.DETAILID=B.POID) AAMOUNT
FROM GTFABPURINWARD A,GTFABPURINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L
WHERE A.GTFABPURINWARDID=B.GTFABPURINWARDID AND B.ORDERNO=C.ORDERNO AND B.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID
AND C.ORDERNO=:ORDERNO
AND A.TTYPE='INWARD'
UNION ALL
SELECT B.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,0-B.RETQTY AQTY,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGFPBILLENTRY AA,GTGFPBILLENTRYDET BB
WHERE AA.GTGFPBILLENTRYID=BB.GTGFPBILLENTRYID AND BB.DETAILID=B.DETAILID) ARATE,
0-(B.RETQTY*(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTGFPBILLENTRY AA,GTGFPBILLENTRYDET BB
WHERE AA.GTGFPBILLENTRYID=BB.GTGFPBILLENTRYID AND BB.DETAILID=B.DETAILID)) AAMOUNT
FROM GTFABPURINWARD A,GTFABPURINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L
WHERE A.GTFABPURINWARDID=B.GTFABPURINWARDID AND B.ORDERNO=C.ORDERNO AND B.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='RETURN'
UNION ALL
SELECT A.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALRECQTY AQTY,
CASE WHEN M.COMPCODE='AGF' AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - KNITTING' THEN B.JOBPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTKNITPROBILL AA,GTKNITPROBILLDET BB
WHERE AA.GTKNITPROBILLID=BB.GTKNITPROBILLID AND BB.DETAILID=B.GTKNITJODETID) END ARATE,B.TOTALRECQTY*
(CASE WHEN M.COMPCODE='AGF' AND A.SUPPLIER='ANUGRAHA FASHION MILL PRIVATE LIMITED - KNITTING' THEN B.JOBPRICE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTKNITPROBILL AA,GTKNITPROBILLDET BB
WHERE AA.GTKNITPROBILLID=BB.GTKNITPROBILLID AND BB.DETAILID=B.GTKNITJODETID) END) AAMOUNT
FROM GTFABRECTOKNIT A,GTFABRECTOKNITDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTCOMPMAST M
WHERE A.GTFABRECTOKNITID=B.GTFABRECTOKNITID AND A.ORDERNO=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND C.COMPCODE=M.GTCOMPMASTID
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT A.TOORDNO ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TRANSQTY1 AQTY,
CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END ARATE,B.TRANSQTY1*
CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END AAMOUNT
FROM GTFTRANS A,TRANSFERSTKDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTFTRANSID=B.GTFTRANSID AND A.TOORDNO=C.ORDERNO AND B.PROCESSNAME3=D.PROCESSNAME AND B.ALIASNAME1=E.FABALIASNAME
AND B.COLOR1=F.COLORNAME AND B.DESIGN1=G.DESIGN AND B.GSM1=H.GSM AND B.GG1=I.GG
AND B.LL1=J.LL AND B.KDIA1=K.DIA AND B.FDIA1=L.DIA AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND D.GTPROCESSMASTID=N.PROCESSNAME
AND C.ORDERNO=:ORDERNO
AND M.PROCESSGROUPNAME='GREY FABRIC'
) GROUP BY PROCESSNAME,FABRIC,COLOR,DESIGN,GSM,GG,LL,KDIA,FDIA,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  GREY_FABRIC_TRANSFER: {
    sql: `SELECT ORDERNO,PROCESSNAME,FABRIC||' / '||COLOR||' / '||DESIGN||' / '||GSM||' / '||GG||' / '||LL||' / '||KDIA||' / '||FDIA DESCRIPTION,UOM,
SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,SUM(PAMOUNT)/SUM(PQTY)) PRATE,
SUM(PAMOUNT) PAMOUNT,0-SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,SUM(AAMOUNT)/SUM(AQTY)) ARATE,0-SUM(AAMOUNT) AAMOUNT,3 AS ORD FROM (
SELECT A.FROMORDNO ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER' ,1,3) TRANSTYPE,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TRANSQTY1 AQTY,
CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END ARATE,
B.TRANSQTY1*CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END AAMOUNT
FROM GTFTRANS A,TRANSFERSTKDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTFTRANSID=B.GTFTRANSID AND A.FROMORDNO=C.ORDERNO AND B.PROCESSNAME3=D.PROCESSNAME AND B.ALIASNAME1=E.FABALIASNAME
AND B.COLOR1=F.COLORNAME AND B.DESIGN1=G.DESIGN AND B.GSM1=H.GSM AND B.GG1=I.GG
AND B.LL1=J.LL AND B.KDIA1=K.DIA AND B.FDIA1=L.DIA AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND D.GTPROCESSMASTID=N.PROCESSNAME
AND C.ORDERNO=:ORDERNO
AND M.PROCESSGROUPNAME='GREY FABRIC'
) GROUP BY PROCESSNAME,TRANSTYPE,FABRIC,COLOR,DESIGN,GSM,GG,LL,KDIA,FDIA,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  DYED_FABRIC_PURCHASE_PROCESS: {
    sql: `SELECT ORDERNO,PROCESSNAME,
FABRIC||' / '||COLOR||' / '||DESIGN||' / '||GSM||' / '||GG||' / '||LL||' / '||KDIA||' / '||FDIA DESCRIPTION,UOM,
SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,SUM(PAMOUNT)/SUM(PQTY)) PRATE,
SUM(PAMOUNT) PAMOUNT,SUM(AQTY) AQTY,ROUND(DECODE(SUM(AAMOUNT),0,0,SUM(AAMOUNT)/SUM(AQTY)),2) ARATE,SUM(AAMOUNT) AAMOUNT,4 AS ORD FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,B.FGQTY PQTY,B.FRATE PRATE,B.FGQTY*B.FRATE PAMOUNT,0 AQTY,0 ARATE,0 AAMOUNT
FROM GTBM A,GTFABDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.FPROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.FCOLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND B.FPROCESSNAME=N.PROCESSNAME AND M.PROCESSGROUPNAME='DYED FABRIC'
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT C.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALGRNQTY AQTY,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDFPBILLENTRY AA,GTDFPBILLENTRYDET BB
WHERE AA.GTDFPBILLENTRYID=BB.GTDFPBILLENTRYID AND BB.DETAILID=B.POID) ARATE,B.TOTALGRNQTY*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDFPBILLENTRY AA,GTDFPBILLENTRYDET BB WHERE AA.GTDFPBILLENTRYID=BB.GTDFPBILLENTRYID AND BB.DETAILID=B.POID) AAMOUNT
FROM GTDFABPURINWARD A,GTDFABPURINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L
WHERE A.GTDFABPURINWARDID=B.GTDFABPURINWARDID AND B.ORDERNO=C.ORDERNO AND B.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='INWARD'
UNION ALL
SELECT C.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,0-B.TOTALGRNQTY AQTY,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDFPBILLENTRY AA,GTDFPBILLENTRYDET BB
WHERE AA.GTDFPBILLENTRYID=BB.GTDFPBILLENTRYID AND BB.DETAILID=B.POID) ARATE,0-(B.TOTALGRNQTY*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTDFPBILLENTRY AA,GTDFPBILLENTRYDET BB WHERE AA.GTDFPBILLENTRYID=BB.GTDFPBILLENTRYID AND BB.DETAILID=B.POID)) AAMOUNT
FROM GTDFABPURINWARD A,GTDFABPURINWARDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L
WHERE A.GTDFABPURINWARDID=B.GTDFABPURINWARDID AND B.ORDERNO=C.ORDERNO AND B.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID
AND C.ORDERNO=:ORDERNO AND A.TTYPE='RETURN'
UNION ALL
SELECT  A.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,ROUND(B.TOTRECQTY+
(B.TOTRECQTY*NVL((SELECT SUM(BB.LOSSQTY)/SUM(BB.RECQTY1)
FROM GTFABPROREC AA,GTFABPRORECSUB BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTFABRICMAST EE,GTCOLORMAST FF,GTDESIGNMAST GG,GTGSMMAST HH,
GTGGMAST II,GTLOOPMAST JJ,GTDIAMAST KK,GTDIAMAST LL
WHERE AA.GTFABPRORECID=BB.GTFABPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID AND BB.FABRIC1=EE.GTFABRICMASTID
AND BB.COLOR1=FF.GTCOLORMASTID AND BB.DESIGN1=GG.GTDESIGNMASTID AND BB.GSM1=HH.GTGSMMASTID AND BB.GG1=II.GTGGMASTID
AND BB.LL1=JJ.GTLOOPMASTID AND BB.KDIA1=KK.GTDIAMASTID AND BB.FDIA1=LL.GTDIAMASTID
AND A.GTFABPRORECID=AA.GTFABPRORECID AND B.FABRIC=BB.FABRIC1 AND B.COLOR=BB.COLOR1 AND C.ORDERNO=:ORDERNO ),0)),3) AQTY,
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) RATE
FROM GTFABPROBILL AA,GTFABPROBILLDET BB,GTFABPRORECDTL CC,GTNORDERENTRY DD,GTPROCESSMAST EE
WHERE AA.GTFABPROBILLID=BB.GTFABPROBILLID AND BB.DETAILID=CC.DETAILID AND BB.ORDERNO=DD.GTNORDERENTRYID
AND BB.PROCESSNAME=EE.GTPROCESSMASTID AND DD.ORDERNO=:ORDERNO and bb.detailid=b.detailid
) ARATE,
ROUND((B.TOTRECQTY+(B.TOTRECQTY*(NVL((SELECT SUM(BB.LOSSQTY)/SUM(BB.RECQTY1)
FROM GTFABPROREC AA,GTFABPRORECSUB BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTFABRICMAST EE,GTCOLORMAST FF,GTDESIGNMAST GG,GTGSMMAST HH,
GTGGMAST II,GTLOOPMAST JJ,GTDIAMAST KK,GTDIAMAST LL
WHERE AA.GTFABPRORECID=BB.GTFABPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID AND BB.FABRIC1=EE.GTFABRICMASTID
AND BB.COLOR1=FF.GTCOLORMASTID AND BB.DESIGN1=GG.GTDESIGNMASTID AND BB.GSM1=HH.GTGSMMASTID AND BB.GG1=II.GTGGMASTID
AND BB.LL1=JJ.GTLOOPMASTID AND BB.KDIA1=KK.GTDIAMASTID AND BB.FDIA1=LL.GTDIAMASTID
AND A.GTFABPRORECID=AA.GTFABPRORECID AND B.FABRIC=BB.FABRIC1 AND B.COLOR=BB.COLOR1 AND C.ORDERNO=:ORDERNO ),0))))*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) RATE
FROM GTFABPROBILL AA,GTFABPROBILLDET BB,GTFABPRORECDTL CC,GTNORDERENTRY DD,GTPROCESSMAST EE
WHERE AA.GTFABPROBILLID=BB.GTFABPROBILLID AND BB.DETAILID=CC.DETAILID AND BB.ORDERNO=DD.GTNORDERENTRYID
AND BB.PROCESSNAME=EE.GTPROCESSMASTID AND DD.ORDERNO=:ORDERNO and bb.detailid=b.detailid),2) AAMOUNT
FROM GTFABPROREC A,GTFABPRORECDTL B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTCOMPMAST M
WHERE A.GTFABPRORECID=B.GTFABPRORECID AND B.ORDERNO1=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND C.COMPCODE=M.GTCOMPMASTID
AND C.ORDERNO=:ORDERNO AND A.SUPPLIER<>'FREELOOK FASHIONS - DYEING DIVISION'
UNION ALL
SELECT A.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.PROQTY AQTY,
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTLFWBILLENTRY AA,GTLFWBILLENTRYDET BB,GTLFWJO CC
WHERE AA.GTLFWBILLENTRYID=BB.GTLFWBILLENTRYID AND BB.JOBNO=CC.GTLFWJOID AND A.JOBNO=CC.GTLFWJOID AND B.COLOR=BB.YARNCOLOR) ARATE,
(B.PROQTY+B.LOSSQTY)*(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTLFWBILLENTRY AA,GTLFWBILLENTRYDET BB,GTLFWJO CC
WHERE AA.GTLFWBILLENTRYID=BB.GTLFWBILLENTRYID AND BB.JOBNO=CC.GTLFWJOID AND A.JOBNO=CC.GTLFWJOID AND B.COLOR=BB.YARNCOLOR) AAMOUNT
FROM GTLFWREC A,GTLFWRECSTK B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L
WHERE A.GTLFWRECID=B.GTLFWRECID AND A.ORDERNO=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID AND B.ALIASNAME=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT A.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALRECQTY AQTY,
CASE WHEN M.COMPCODE='FLF' AND A.SUPPLIER='FREELOOK FASHIONS' THEN B.JOBRATE
ELSE (SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTCOLKNITBILL AA,GTCOLKNITBILLDET BB,GTCOLKNITJO CC
WHERE AA.GTCOLKNITBILLID=BB.GTCOLKNITBILLID AND BB.JOBNO=CC.GTCOLKNITJOID AND BB.DETAILID=B.DETAILID) END ARATE,
CASE WHEN M.COMPCODE='FLF' AND A.SUPPLIER='FREELOOK FASHIONS' THEN B.TOTALRECQTY*B.JOBRATE
ELSE B.TOTALRECQTY*(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTCOLKNITBILL AA,GTCOLKNITBILLDET BB,GTCOLKNITJO CC
WHERE AA.GTCOLKNITBILLID=BB.GTCOLKNITBILLID AND BB.JOBNO=CC.GTCOLKNITJOID AND BB.DETAILID=B.DETAILID) END AAMOUNT
FROM GTCOLKNITREC A,GTCOLKNITRECDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTCOMPMAST M
WHERE A.GTCOLKNITRECID=B.GTCOLKNITRECID AND A.ORDERNO=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND C.COMPCODE=M.GTCOMPMASTID
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT A.ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTRECQTY+
(B.TOTRECQTY*NVL((SELECT SUM(BB.LOSSQTY)/SUM(BB.RECQTY1)
FROM GTCOLPROREC AA,GTCOLPRORECSUB BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTFABRICMAST EE,GTCOLORMAST FF,GTDESIGNMAST GG,GTGSMMAST HH,
GTGGMAST II,GTLOOPMAST JJ,GTDIAMAST KK,GTDIAMAST LL
WHERE AA.GTCOLPRORECID=BB.GTCOLPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID AND BB.FABRIC1=EE.GTFABRICMASTID
AND BB.COLOR1=FF.GTCOLORMASTID AND BB.DESIGN1=GG.GTDESIGNMASTID AND BB.GSM1=HH.GTGSMMASTID AND BB.GG1=II.GTGGMASTID
AND BB.LL1=JJ.GTLOOPMASTID AND BB.KDIA1=KK.GTDIAMASTID AND BB.FDIA1=LL.GTDIAMASTID
AND A.GTCOLPRORECID=AA.GTCOLPRORECID AND B.FABRIC=BB.FABRIC1 AND B.COLOR=BB.COLOR1 AND C.ORDERNO=:ORDERNO
),0)) AQTY,
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTCOLPROBILL AA,GTCOLPROBILLDET BB,GTCOLPROJOBORD CC
WHERE AA.GTCOLPROBILLID=BB.GTCOLPROBILLID AND BB.JOBNO=CC.GTCOLPROJOBORDID AND BB.DETAILID=B.DETAILID) ARATE,
(B.TOTRECQTY+(B.TOTRECQTY*(NVL((SELECT SUM(BB.LOSSQTY)/SUM(BB.RECQTY1)
FROM GTCOLPROREC AA,GTCOLPRORECSUB BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTFABRICMAST EE,GTCOLORMAST FF,GTDESIGNMAST GG,GTGSMMAST HH,
GTGGMAST II,GTLOOPMAST JJ,GTDIAMAST KK,GTDIAMAST LL
WHERE AA.GTCOLPRORECID=BB.GTCOLPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.PROCESSNAME=DD.GTPROCESSMASTID AND BB.FABRIC1=EE.GTFABRICMASTID
AND BB.COLOR1=FF.GTCOLORMASTID AND BB.DESIGN1=GG.GTDESIGNMASTID AND BB.GSM1=HH.GTGSMMASTID AND BB.GG1=II.GTGGMASTID
AND BB.LL1=JJ.GTLOOPMASTID AND BB.KDIA1=KK.GTDIAMASTID AND BB.FDIA1=LL.GTDIAMASTID
AND A.GTCOLPRORECID=AA.GTCOLPRORECID AND B.FABRIC=BB.FABRIC1 AND B.COLOR=BB.COLOR1 AND C.ORDERNO=:ORDERNO
),0))))*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTCOLPROBILL AA,GTCOLPROBILLDET BB,GTCOLPROJOBORD CC
WHERE AA.GTCOLPROBILLID=BB.GTCOLPROBILLID AND BB.JOBNO=CC.GTCOLPROJOBORDID AND BB.DETAILID=B.DETAILID) AAMOUNT
FROM GTCOLPROREC A,GTCOLPRORECDTL B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTCOMPMAST M
WHERE A.GTCOLPRORECID=B.GTCOLPRORECID AND A.ORDERNO=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID AND B.FABRIC=E.GTFABRICMASTID
AND B.COLOR=F.GTCOLORMASTID AND B.DESIGN=G.GTDESIGNMASTID AND B.GSM=H.GTGSMMASTID AND B.GG=I.GTGGMASTID
AND B.LL=J.GTLOOPMASTID AND B.KDIA=K.GTDIAMASTID AND B.FDIA=L.GTDIAMASTID AND C.COMPCODE=M.GTCOMPMASTID
AND C.ORDERNO=:ORDERNO
AND A.SUPPLIER<>'FREELOOK FASHIONS - DYEING DIVISION'
UNION ALL
SELECT A.TOORDNO ORDERNO,D.PROCESSNAME,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TRANSQTY1 AQTY,
CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END ARATE,
B.TRANSQTY1*CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END AAMOUNT
FROM GTFTRANS A,TRANSFERSTKDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTFTRANSID=B.GTFTRANSID AND A.TOORDNO=C.ORDERNO AND B.PROCESSNAME3=D.PROCESSNAME AND B.ALIASNAME1=E.FABALIASNAME
AND B.COLOR1=F.COLORNAME AND B.DESIGN1=G.DESIGN AND B.GSM1=H.GSM AND B.GG1=I.GG
AND B.LL1=J.LL AND B.KDIA1=K.DIA AND B.FDIA1=L.DIA AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND D.GTPROCESSMASTID=N.PROCESSNAME
AND C.ORDERNO=:ORDERNO
AND M.PROCESSGROUPNAME='DYED FABRIC'
)
GROUP BY PROCESSNAME,FABRIC,COLOR,DESIGN,GSM,GG,LL,KDIA,FDIA,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  DYED_FABRIC_TRANSFER: {
    sql: `SELECT ORDERNO,PROCESSNAME,FABRIC||' / '||COLOR||' / '||DESIGN||' / '||GSM||' / '||GG||' / '||LL||' / '||KDIA||' / '||FDIA DESCRIPTION,UOM,
SUM(PQTY) PQTY,DECODE(SUM(PAMOUNT),0,0,SUM(PAMOUNT)/SUM(PQTY)) PRATE,
SUM(PAMOUNT) PAMOUNT,SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,SUM(AAMOUNT)/SUM(AQTY)) ARATE,SUM(AAMOUNT) AAMOUNT,4 AS ORD FROM (
SELECT A.FROMORDNO ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER' ,1,3) TRANSTYPE,E.FABALIASNAME FABRIC,F.COLORNAME COLOR,G.DESIGN,H.GSM,I.GG,J.LL,
K.DIA KDIA,L.DIA FDIA,'KGS' UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TRANSQTY1 AQTY,
CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END ARATE,
B.TRANSQTY1*CASE WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NULL THEN B.STORATE
WHEN A.FROMORDNO='GENERAL' AND B.NEWRATE IS NOT NULL THEN B.NEWRATE ELSE B.STORATE END AAMOUNT
FROM GTFTRANS A,TRANSFERSTKDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTFABRICMAST E,GTCOLORMAST F,GTDESIGNMAST G,GTGSMMAST H,GTGGMAST I,
GTLOOPMAST J,GTDIAMAST K,GTDIAMAST L,GTPROGROUPMAST M,GTPROGRPDETAIL N
WHERE A.GTFTRANSID=B.GTFTRANSID AND A.FROMORDNO=C.ORDERNO AND B.PROCESSNAME3=D.PROCESSNAME AND B.ALIASNAME1=E.FABALIASNAME
AND B.COLOR1=F.COLORNAME AND B.DESIGN1=G.DESIGN AND B.GSM1=H.GSM AND B.GG1=I.GG
AND B.LL1=J.LL AND B.KDIA1=K.DIA AND B.FDIA1=L.DIA AND M.GTPROGROUPMASTID=N.GTPROGROUPMASTID
AND D.GTPROCESSMASTID=N.PROCESSNAME
AND C.ORDERNO=:ORDERNO
AND M.PROCESSGROUPNAME='DYED FABRIC'
) GROUP BY PROCESSNAME,TRANSTYPE,FABRIC,COLOR,DESIGN,GSM,GG,LL,KDIA,FDIA,UOM,ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
      "ord",
    ],
  },

  ACCESSORY_PURCHASE: {
    sql: `SELECT X.* FROM (
SELECT A.ORDERNO,A.PROCESSNAME,A.ACCNAME DESCRIPTION,A.UOM,SUM(A.PQTY) PQTY,DECODE(SUM(A.PAMOUNT),0,0,ROUND(SUM(A.PAMOUNT)/SUM(A.PQTY),2)) PRATE,
SUM(A.PAMOUNT) PAMOUNT,SUM(A.AQTY) AQTY,DECODE(SUM(A.AAMOUNT),0,0,ROUND(SUM(A.AAMOUNT)/SUM(A.AQTY),2)) ARATE,ROUND(SUM(A.AAMOUNT),2) AAMOUNT
FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,B.ACCROUNDQTY PQTY,B.ACCRATE PRATE,B.ACCAMOUNT PAMOUNT,0 AQTY,0 ISSUEQTY,0 ARATE,0 AAMOUNT ,0 AAMOUNT1,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTBM A,GTBMACCDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.ACCPROCESSNAME=D.GTPROCESSMASTID
AND B.ACCNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZES=G.GTSIZEMASTID
AND B.ACCUOM=H.GTUNITMASTID AND D.PROCESSNAME IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT AA.ORDERNO,AA.PROCESSNAME,AA.ACCNAME,AA.COLOR,AA.SIZES,AA.UOM,AA.PQTY,AA.PRATE,AA.PAMOUNT ,
SUM(AA.AQTY) AQTY,0 ISSUEQTY,DECODE(SUM(AQTY),0,0,ROUND(SUM(AA.AAMOUNT)/SUM(AA.AQTY),2)) ARATE,ROUND(SUM(AA.AAMOUNT),2) AAMOUNT,0 AAMOUNT1,AA.ACCORD
FROM (
SELECT AA.ORDERNO,AA.PROCESSNAME,AA.ACCNAME,AA.COLOR,AA.SIZES,AA.UOM,AA.PQTY,AA.PRATE,AA.PAMOUNT,AA.GENERAL,SUM(AA.AQTY) AQTY,AVG(AA.ARATE) ARATE,SUM(AA.AAMOUNT) AAMOUNT,AA.ACCORD FROM (
SELECT B.ORDERNO,D.PROCESSNAME,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,
SUM(B.TOTALGRNQTY)-NVL((SELECT SUM(BBB.RETQTY)
FROM GTACCPOINWARD AAA,GTACCPOINWARDDTL BBB,GTNORDERENTRY CCC,GTPROCESSMAST DDD,GTACCMAST EEE,GTCOLORMAST FFF,
GTSIZEMAST GGG,GTUNITMAST HHH
WHERE AAA.GTACCPOINWARDID=BBB.GTACCPOINWARDID AND BBB.ORDERNO=CCC.ORDERNO AND BBB.PURCHTYPE=DDD.GTPROCESSMASTID
AND BBB.ALIASNAME=EEE.GTACCMASTID AND BBB.ACCCOLOR=FFF.GTCOLORMASTID AND BBB.ACCSIZE=GGG.GTSIZEMASTID
AND BBB.UOM=HHH.GTUNITMASTID AND AAA.TTYPE='RETURN' AND BBB.GTACCPODETID=B.GTACCPODETID
AND CCC.ORDERNO=:ORDERNO),0) AQTY,NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTACCPBILLENTRY AA,GTACCPBILLENTRYDET BB,GTACCPO CC
WHERE AA.GTACCPBILLENTRYID=BB.GTACCPBILLENTRYID AND BB.DETAILID=B.GTACCPODETID),0) ARATE,0 ISSUEQTY,
 NVL(SUM(B.TOTALGRNQTY)-NVL((SELECT SUM(BBB.RETQTY)
FROM GTACCPOINWARD AAA,GTACCPOINWARDDTL BBB,GTNORDERENTRY CCC,GTPROCESSMAST DDD,GTACCMAST EEE,GTCOLORMAST FFF,
GTSIZEMAST GGG,GTUNITMAST HHH
WHERE AAA.GTACCPOINWARDID=BBB.GTACCPOINWARDID AND BBB.ORDERNO=CCC.ORDERNO AND BBB.PURCHTYPE=DDD.GTPROCESSMASTID
AND BBB.ALIASNAME=EEE.GTACCMASTID AND BBB.ACCCOLOR=FFF.GTCOLORMASTID AND BBB.ACCSIZE=GGG.GTSIZEMASTID
AND BBB.UOM=HHH.GTUNITMASTID AND AAA.TTYPE='RETURN' AND BBB.GTACCPODETID=B.GTACCPODETID
AND CCC.ORDERNO=:ORDERNO),0),0)*NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTACCPBILLENTRY AA,GTACCPBILLENTRYDET BB,GTACCPO CC
WHERE AA.GTACCPBILLENTRYID=BB.GTACCPBILLENTRYID AND BB.DETAILID=B.GTACCPODETID),0)  AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD,E.GENERAL
FROM GTACCPOINWARD A,GTACCPOINWARDDTL B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCPOINWARDID=B.GTACCPOINWARDID AND B.ORDERNO=C.ORDERNO AND B.PURCHTYPE=D.GTPROCESSMASTID
AND B.ALIASNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZE=G.GTSIZEMASTID
AND B.UOM=H.GTUNITMASTID AND A.TTYPE='INWARD'
AND C.ORDERNO=:ORDERNO
GROUP BY B.ORDERNO,D.PROCESSNAME,E.ALIASNAME,F.COLORNAME,G.SIZENAME,H.UNITNAME,E.GENERAL,E.ACCCAT,B.GTACCPODETID
) AA
GROUP BY AA.ORDERNO,AA.PROCESSNAME,AA.ACCNAME,AA.COLOR,AA.SIZES,AA.UOM,AA.PQTY,AA.PRATE,AA.PAMOUNT,AA.GENERAL,AA.ACCORD
) AA
GROUP BY AA.ORDERNO,AA.PROCESSNAME,AA.ACCNAME,AA.COLOR,AA.SIZES,AA.UOM,AA.PQTY,AA.PRATE,AA.PAMOUNT,AA.GENERAL,AA.ACCORD
UNION ALL
SELECT A.ORDERNO,A.PROCESSNAME,A.ACCNAME,A.COLOR,A.SIZES,A.UOM,A.PQTY, A.PRATE, A.PAMOUNT,
SUM(A.AQTY) AQTY,ROUND(SUM(AAMOUNT)/SUM(A.AQTY),2) ARATE,0 ISSUEQTY,SUM(AAMOUNT) AAMOUNT,SUM(AAMOUNT) AAMOUNT1,1 ACCORD
FROM (
 SELECT A.TOORDER ORDERNO,D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,SUM(B.FTRANSFERQTY) AQTY,E.GENERAL,
CASE WHEN A.FROMORDER='GENERAL' THEN ROUND(( SELECT SUM(AAA.AMOUNT)/SUM(AAA.QTY) FROM (
SELECT BB.TRANSFERQTY QTY,BB.RATE,ROUND(BB.TRANSFERQTY*BB.RATE,3) AMOUNT,DD.ALIASNAME ACCNAME,EE.COLORNAME ACCCOLOR,FF.SIZENAME ACCSIZE,AA.GTACCSTKTRANSID
FROM GTACCSTKTRANS AA,GTACCSTKTRANSDET BB,GTNORDERENTRY CC,GTACCMAST DD,GTCOLORMAST EE,GTSIZEMAST FF
WHERE AA.GTACCSTKTRANSID=BB.GTACCSTKTRANSID AND AA.TOORDER=CC.ORDERNO AND BB.ACCNAME=DD.GTACCMASTID
AND BB.ACCCOLOR=EE.GTCOLORMASTID AND BB.ACCSIZE=FF.GTSIZEMASTID
) AAA WHERE AAA.ACCNAME=E.ALIASNAME AND AAA.ACCCOLOR=F.COLORNAME AND (AAA.ACCSIZE=G.NEWSIZE OR G.NEWSIZE='ALL' OR AAA.ACCSIZE='ALL') AND AAA.GTACCSTKTRANSID=A.GTACCSTKTRANSID
),2) ELSE B.FRATE END ARATE,
SUM(B.FTRANSFERQTY)*(CASE WHEN A.FROMORDER='GENERAL' THEN ROUND(( SELECT SUM(AAA.AMOUNT)/SUM(AAA.QTY) FROM (
SELECT BB.TRANSFERQTY QTY,BB.RATE,ROUND(BB.TRANSFERQTY*BB.RATE,2) AMOUNT,DD.ALIASNAME ACCNAME,EE.COLORNAME ACCCOLOR,FF.SIZENAME ACCSIZE,AA.GTACCSTKTRANSID
FROM GTACCSTKTRANS AA,GTACCSTKTRANSDET BB,GTNORDERENTRY CC,GTACCMAST DD,GTCOLORMAST EE,GTSIZEMAST FF
WHERE AA.GTACCSTKTRANSID=BB.GTACCSTKTRANSID AND AA.TOORDER=CC.ORDERNO AND BB.ACCNAME=DD.GTACCMASTID
AND BB.ACCCOLOR=EE.GTCOLORMASTID AND BB.ACCSIZE=FF.GTSIZEMASTID
) AAA WHERE AAA.ACCNAME=E.ALIASNAME AND AAA.ACCCOLOR=F.COLORNAME AND (AAA.ACCSIZE=G.NEWSIZE OR G.NEWSIZE='ALL' OR AAA.ACCSIZE='ALL') AND AAA.GTACCSTKTRANSID=A.GTACCSTKTRANSID
),3) ELSE B.FRATE END) AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTACCSTKTRANS A,GTACCFRMORDDET B,GTNORDERENTRY C,GTPROCESSMAST D
,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCSTKTRANSID=B.GTACCSTKTRANSID AND A.TOORDER=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID
AND B.FACCNAME=E.GTACCMASTID AND B.FACCCOLOR=F.GTCOLORMASTID AND B.FACCSIZE=G.GTSIZEMASTID
AND B.FACCUOM=H.GTUNITMASTID AND D.PROCESSNAME IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
GROUP BY A.TOORDER,D.PROCESSNAME,SUBSTR('TRANSFER',1,3),E.ALIASNAME,F.COLORNAME,G.SIZENAME,H.UNITNAME,A.FROMORDER,A.GTACCSTKTRANSID,
B.FACCNAME,B.FACCCOLOR,B.FRATE,E.ACCCAT,E.GENERAL,G.NEWSIZE
) A
GROUP BY ORDERNO,PROCESSNAME,TRANSTYPE,ACCNAME, COLOR, SIZES,UOM, PQTY, PRATE, PAMOUNT,GENERAL
) A GROUP BY A.PROCESSNAME,A.ACCNAME,A.UOM,A.ACCORD,A.ORDERNO
) X
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
    ],
  },

  ACCESSORY_PURCHASE_TRANSFER: {
    sql: `SELECT A.ORDERNO,A.PROCESSNAME,A.ACCNAME DESCRIPTION,A.UOM,SUM(A.PQTY) PQTY,DECODE(SUM(A.PAMOUNT),0,0,ROUND(SUM(A.PAMOUNT)/SUM(A.PQTY),2)) PRATE,
SUM(A.PAMOUNT) PAMOUNT,SUM(A.AQTY) AQTY,DECODE(SUM(A.AAMOUNT),0,0,ROUND(SUM(A.AAMOUNT)/SUM(A.AQTY),2)) ARATE,SUM(A.AAMOUNT) AAMOUNT FROM (
SELECT A.FROMORDER ORDERNO, D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,0-B.TRANSFERQTY AQTY,0 ISSUEQTY,B.RATE ARATE,0-(B.TRANSFERQTY*B.RATE) AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTACCSTKTRANS A,GTACCSTKTRANSDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCSTKTRANSID=B.GTACCSTKTRANSID AND A.FROMORDER=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID
AND B.ACCNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZE=G.GTSIZEMASTID
AND B.ACCUOM=H.GTUNITMASTID AND D.PROCESSNAME IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
) A GROUP BY A.PROCESSNAME,A.TRANSTYPE,A.ACCNAME,A.UOM,A.ACCORD,A.ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
    ],
  },

  ACCESSORY_PROCESS: {
    sql: `SELECT A.PROCESSNAME,A.ACCNAME DESCRIPTION,A.UOM,SUM(A.PQTY) PQTY,DECODE(SUM(A.PAMOUNT),0,0,ROUND(SUM(A.PAMOUNT)/SUM(A.PQTY),2)) PRATE,
SUM(A.PAMOUNT) PAMOUNT,SUM(A.AQTY) AQTY,DECODE(SUM(A.AAMOUNT),0,0,ROUND(SUM(A.AAMOUNT)/SUM(A.AQTY),2)) ARATE,SUM(A.AAMOUNT) AAMOUNT
FROM (
SELECT C.ORDERNO,D.PROCESSNAME,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,B.ACCROUNDQTY PQTY,B.ACCRATE PRATE,B.ACCAMOUNT PAMOUNT,0 AQTY,0 ISSUEQTY,0 ARATE,0 AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTBM A,GTBMACCDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.ACCPROCESSNAME=D.GTPROCESSMASTID
AND B.ACCNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZES=G.GTSIZEMASTID
AND B.ACCUOM=H.GTUNITMASTID AND D.PROCESSNAME NOT IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT A.ORDERNO,D.PROCESSNAME,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.TOTALRECQTY+NVL((SELECT DECODE(SUM(BB.ISSRECQTY),0,0,SUM(BB.LOSSQTY)/SUM(BB.ISSRECQTY))
FROM GTACCPROREC AA,GTACCPRORECSTOCK BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTACCMAST EE,GTCOLORMAST FF,GTSIZEMAST GG,GTUNITMAST HH
WHERE AA.GTACCPRORECID=BB.GTACCPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.APROCESS=DD.GTPROCESSMASTID
AND BB.ACCNAME1=EE.GTACCMASTID AND BB.ACCCOLOR1=FF.GTCOLORMASTID AND BB.ACCSIZE1=GG.GTSIZEMASTID
AND BB.ACCUOM1=HH.GTUNITMASTID AND A.GTACCPRORECID=AA.GTACCPRORECID AND B.ACCNAME=BB.ACCNAME1 AND B.ACCSIZE=BB.ACCSIZE1
),0) AQTY,0 ISSUEQTY,NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTACCPROBILL AA,GTACCPROBILLDET BB
WHERE AA.GTACCPROBILLID=BB.GTACCPROBILLID AND BB.DETAILID=B.GTACCPROJODTLID),0) ARATE,(B.TOTALRECQTY+(B.TOTALRECQTY*(NVL((SELECT DECODE(SUM(BB.ISSRECQTY),0,0,SUM(BB.LOSSQTY)/SUM(BB.ISSRECQTY))
FROM GTACCPROREC AA,GTACCPRORECSTOCK BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTACCMAST EE,GTCOLORMAST FF,GTSIZEMAST GG,GTUNITMAST HH
WHERE AA.GTACCPRORECID=BB.GTACCPRORECID AND AA.ORDERNO=CC.ORDERNO AND AA.APROCESS=DD.GTPROCESSMASTID
AND BB.ACCNAME1=EE.GTACCMASTID AND BB.ACCCOLOR1=FF.GTCOLORMASTID AND BB.ACCSIZE1=GG.GTSIZEMASTID
AND BB.ACCUOM1=HH.GTUNITMASTID AND A.GTACCPRORECID=AA.GTACCPRORECID AND B.ACCNAME=BB.ACCNAME1 AND B.ACCSIZE=BB.ACCSIZE1
),0))))*NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTACCPROBILL AA,GTACCPROBILLDET BB
WHERE AA.GTACCPROBILLID=BB.GTACCPROBILLID AND BB.DETAILID=B.GTACCPROJODTLID),0) AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTACCPROREC A,GTACCPRORECDTL B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCPRORECID=B.GTACCPRORECID AND A.ORDERNO=C.ORDERNO AND A.APROCESS=D.GTPROCESSMASTID
AND B.ACCNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZE=G.GTSIZEMASTID
AND B.UOM=H.GTUNITMASTID
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT A.TOORDER ORDERNO,D.PROCESSNAME,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,B.FTRANSFERQTY AQTY,0 ISSUEQTY,
(CASE WHEN A.FROMORDER='GENERAL' THEN NVL((SELECT AVG(BB.RATE)
FROM GTACCSTKTRANS AA,GTACCSTKTRANSDET BB,GTNORDERENTRY CC
WHERE AA.GTACCSTKTRANSID=BB.GTACCSTKTRANSID AND AA.TOORDER=CC.ORDERNO AND AA.GTACCSTKTRANSID=A.GTACCSTKTRANSID
AND BB.ACCNAME=B.FACCNAME AND BB.ACCCOLOR=B.FACCCOLOR),0) ELSE B.FRATE END) ARATE,
B.FTRANSFERQTY*(CASE WHEN A.FROMORDER='GENERAL' THEN NVL((SELECT AVG(BB.RATE)
FROM GTACCSTKTRANS AA,GTACCSTKTRANSDET BB,GTNORDERENTRY CC
WHERE AA.GTACCSTKTRANSID=BB.GTACCSTKTRANSID AND AA.TOORDER=CC.ORDERNO AND AA.GTACCSTKTRANSID=A.GTACCSTKTRANSID
AND BB.ACCNAME=B.FACCNAME AND BB.ACCCOLOR=B.FACCCOLOR),0) ELSE B.FRATE END) AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTACCSTKTRANS A,GTACCFRMORDDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCSTKTRANSID=B.GTACCSTKTRANSID AND A.TOORDER=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID
AND B.FACCNAME=E.GTACCMASTID AND B.FACCCOLOR=F.GTCOLORMASTID AND B.FACCSIZE=G.GTSIZEMASTID
AND B.FACCUOM=H.GTUNITMASTID AND D.PROCESSNAME NOT IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
) A GROUP BY A.PROCESSNAME,A.ACCNAME,A.UOM,A.ACCORD,A.ORDERNO
ORDER BY 3,2,1`,
    fields: [
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
    ],
  },

  ACCESSORY_PROCESS_TRANSFER: {
    sql: `SELECT A.ORDERNO,A.PROCESSNAME,A.ACCNAME DESCRIPTION,A.UOM,SUM(A.PQTY) PQTY,DECODE(SUM(A.PAMOUNT),0,0,ROUND(SUM(A.PAMOUNT)/SUM(A.PQTY),2)) PRATE,
SUM(A.PAMOUNT) PAMOUNT,SUM(A.AQTY) AQTY,DECODE(SUM(A.AAMOUNT),0,0,ROUND(SUM(A.AAMOUNT)/SUM(A.AQTY),2)) ARATE,SUM(A.AAMOUNT) AAMOUNT FROM (
SELECT A.FROMORDER ORDERNO, D.PROCESSNAME,SUBSTR('TRANSFER',1,3) TRANSTYPE,E.ALIASNAME ACCNAME,F.COLORNAME COLOR,G.SIZENAME SIZES,
H.UNITNAME UOM,0 PQTY,0 PRATE,0 PAMOUNT,0-B.TRANSFERQTY AQTY,0 ISSUEQTY,B.RATE ARATE,0-(B.TRANSFERQTY*B.RATE) AAMOUNT ,
DECODE(E.ACCCAT,'PACKING ACCESSORIES',2,1) ACCORD
FROM GTACCSTKTRANS A,GTACCSTKTRANSDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTACCMAST E,GTCOLORMAST F,GTSIZEMAST G,GTUNITMAST H
WHERE A.GTACCSTKTRANSID=B.GTACCSTKTRANSID AND A.FROMORDER=C.ORDERNO AND A.PROCESSNAME=D.GTPROCESSMASTID
AND B.ACCNAME=E.GTACCMASTID AND B.ACCCOLOR=F.GTCOLORMASTID AND B.ACCSIZE=G.GTSIZEMASTID
AND B.ACCUOM=H.GTUNITMASTID AND D.PROCESSNAME NOT IN ('RAW MATERIAL PURCHASE','FINISHED GOODS')
AND C.ORDERNO=:ORDERNO
) A GROUP BY A.PROCESSNAME,A.ACCNAME,A.UOM,A.ACCORD,A.ORDERNO
ORDER BY 4,3,2`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
    ],
  },

  CUTTING_MAKING_TRIMMING: {
    sql: `SELECT X.ORDERNO,X.PROCESSNAME,X.DESCRIPTION,X.UOM,X.PQTY,X.PRATE,X.PAMOUNT,X.AQTY,X.ARATE,X.AAMOUNT FROM
( SELECT ORDERNO,TRANSTYPE,PROCESSNAME,STYLEITEM||' / '||COMBO||' / '||COLOR DESCRIPTION,UOM,SUM(PQTY) PQTY,
DECODE(SUM(PAMOUNT),0,0,ROUND(SUM(PAMOUNT)/SUM(PQTY),2)) PRATE,
SUM(PAMOUNT) PAMOUNT,SUM(AQTY) AQTY,DECODE(SUM(AAMOUNT),0,0,ROUND(SUM(AAMOUNT)/SUM(AQTY),2)) ARATE,SUM(AAMOUNT) AAMOUNT FROM (
SELECT C.ORDERNO,D.PROCESSNAME,SUBSTR('PLANNING',1,3) TRANSTYPE,E.STYLEITEM,H. COMBONAME COMBO,F.COLORNAME COLOR,G.SIZENAME,'PIECES' UOM,
B.CREQQTY PQTY,B.CMTRATE PRATE,B.CMTAMOUNT PAMOUNT,0 AQTY,0 ARATE,0 AAMOUNT
FROM GTBM A,GTBMCMTDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTSTYLEITEMMAST E,GTCOLORMAST F,GTSIZEMAST G,GTCOMBOMAST H
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.CPROCESSNAME=D.GTPROCESSMASTID
AND B.ITEM=E.STYLEITEM AND B.CCOLOR=F.COLORNAME AND B.CSIZES=G.SIZENAME AND B.CCOMBO=H.COMBONAME
AND C.ORDERNO=:ORDERNO
UNION ALL
SELECT C.ORDERNO,D.PROCESSNAME,SUBSTR('PLANNING',1,3) TRANSTYPE,E.STYLEITEM,H. COMBONAME COMBO,F.COLORNAME COLOR,G.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.CREQQTY AQTY,B.CMTRATE ARATE,B.CMTAMOUNT AAMOUNT
FROM GTBM A,GTBMCMTDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTSTYLEITEMMAST E,GTCOLORMAST F,GTSIZEMAST G,GTCOMBOMAST H
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.CPROCESSNAME=D.GTPROCESSMASTID
AND B.ITEM=E.STYLEITEM AND B.CCOLOR=F.COLORNAME AND B.CSIZES=G.SIZENAME AND B.CCOMBO=H.COMBONAME
AND C.ORDERNO=:ORDERNO AND D.PROCESSNAME IN ('ALL OVER EMBROIDERY','EMBOSSED PRINTING','EMBROIDERY','FOIL PRINTING',
'GLITTER PRINTING','HAND EMBROIDERY','PORTION PRINTING','PORTION PRINTING I','ROLL EMBROIDERY','SEQUENCE EMBROIDERY','SUBLIMATION PRINTING','YOKE PRINTING','CHEST PRINTING')
UNION ALL
SELECT A.ORDERNO,'CUTTING' PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.RECQTY AQTY,NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0)  ARATE,
B.RECQTY*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0) AAMOUNT
FROM GTCUTREC A,GTCUTRECDET B,GTNORDERENTRY D,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST J
WHERE A.GTCUTRECID=B.GTCUTRECID AND A.ORDERNO=D.ORDERNO
AND A.ITEM=F.GTSTYLEITEMMASTID AND B.COMBO=G.GTCOMBOMASTID AND B.COLOR=H.GTCOLORMASTID
AND B.SIZENAME=I.GTSIZEMASTID AND A.COMPCODE=J.GTCOMPMASTID AND D.ORDERNO=:ORDERNO
AND A.SUPPLIER IN ('ANUGRAHA FASHION MILL PRIVATE LIMITED GARMENT DIVISION UNIT II - CUTTING')
AND h.COLORNAME NOT IN (SELECT C.COLORNAME FROM GTBM A,GTBMCMTDET B,GTCOLORMAST C,GTPROCESSMAST D,GTNORDERENTRY E
WHERE A.GTBMID=B.GTBMID AND B.CPROCESSNAME=D.GTPROCESSMASTID AND B.CCOLOR=C.COLORNAME
AND A.ORDERNO=E.GTNORDERENTRYID AND E.ORDERNO=:ORDERNO
AND D.PROCESSNAME IN ('PORTION PRINTING','CHEST PRINTING'))
UNION ALL
SELECT A.ORDERNO,'CUTTING' PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.RECQTY AQTY,NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0)  ARATE,
B.RECQTY*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0) AAMOUNT
FROM GTCUTREC A,GTCUTRECDET B,GTNORDERENTRY D,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST J
WHERE A.GTCUTRECID=B.GTCUTRECID AND A.ORDERNO=D.ORDERNO
AND A.ITEM=F.GTSTYLEITEMMASTID AND B.COMBO=G.GTCOMBOMASTID AND B.COLOR=H.GTCOLORMASTID
AND B.SIZENAME=I.GTSIZEMASTID AND A.COMPCODE=J.GTCOMPMASTID AND D.ORDERNO=:ORDERNO
AND A.SUPPLIER IN ('VELAV GARMENTS INDIA PRIVATE LIMITED - CUTTING')
UNION ALL
SELECT A.ORDERNO,'CUTTING' PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.RECQTY AQTY,NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0)  ARATE,
B.RECQTY*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO
AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0) AAMOUNT
FROM GTCUTREC A,GTCUTRECDET B,GTNORDERENTRY D,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST J
WHERE A.GTCUTRECID=B.GTCUTRECID AND A.ORDERNO=D.ORDERNO
AND A.ITEM=F.GTSTYLEITEMMASTID AND B.COMBO=G.GTCOMBOMASTID AND B.COLOR=H.GTCOLORMASTID
AND B.SIZENAME=I.GTSIZEMASTID AND A.COMPCODE=J.GTCOMPMASTID AND D.ORDERNO=:ORDERNO
AND A.SUPPLIER='FREELOOK FASHIONS - CUTTING'
UNION ALL
SELECT D.ORDERNO,'CUTTING' PROCESSNAME,SUBSTR('PLANNING',1,3) TRANSTYPE,F.STYLEITEM,
D.COMBO COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,SUM(BB.DELPCSQTY) AQTY,NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0) ARATE,
SUM(BB.DELPCSQTY)*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME='CUTTING' AND EE.COLORNAME=H.COLORNAME),0) AAMOUNT
FROM CTPCSDELCHAL A,CTPCSDELCHALDET B,CTDCSIZEWISEDET BB,
( SELECT DISTINCT D.ORDERNO,D.STYLEITEM,D.COLOR,D.COMBO FROM ORDERALLOWDET D ) D,
GTSTYLEITEMMAST F,GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST J
WHERE A.CTPCSDELCHALID=B.CTPCSDELCHALID AND B.CTPCSDELCHALID=BB.CTPCSDELCHALID AND BB.CTPCSDELCHALID=A.CTPCSDELCHALID
AND B.CTPCSDELCHALDETID = BB.CTPCSDELCHALDETID AND A.FILENO =D.ORDERNO AND D.COLOR = H.COLORNAME
AND D.STYLEITEM =F.STYLEITEM AND B.COLOR=H.GTCOLORMASTID
AND BB.SIZENAME1 =I.SIZENAME AND A.COMPCODE=J.GTCOMPMASTID AND D.ORDERNO=:ORDERNO
AND A.PGRNNO NOT IN (SELECT DISTINCT A.PGRNNO FROM CTPRODUCTION A WHERE A.RIB = 'YES')
AND h.COLORNAME IN (SELECT C.COLORNAME FROM GTBM A,GTBMCMTDET B,GTCOLORMAST C,GTPROCESSMAST D,GTNORDERENTRY E
WHERE A.GTBMID=B.GTBMID AND B.CPROCESSNAME=D.GTPROCESSMASTID AND B.CCOLOR=C.COLORNAME
AND A.ORDERNO=E.GTNORDERENTRYID AND E.ORDERNO=:ORDERNO
AND D.PROCESSNAME IN ('PORTION PRINTING','CHEST PRINTING'))
AND D.ORDERNO IN (
SELECT C.ORDERNO
FROM GTBM A,GTBMCMTDET B,GTNORDERENTRY C,GTPROCESSMAST D
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.CPROCESSNAME=D.GTPROCESSMASTID
AND C.ORDERNO=:ORDERNO AND ( D.PROCESSNAME LIKE '% PRINTING' OR
D.PROCESSNAME LIKE '% PRINTING %' OR
D.PROCESSNAME LIKE 'PRINTING %'))
GROUP BY F.STYLEITEM,D.COMBO,H.COLORNAME,I.SIZENAME,D.ORDERNO
UNION ALL
SELECT B.ORDERNO,E.PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,C.DAILYPROD AQTY,
CASE WHEN J.COMPNAME IN ('ANUGRAHA FASHION MILL PRIVATE LIMITED','FREELOOK FASHIONS','VELAV GARMENTS INDIA PRIVATE LIMITED')
THEN NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2)
FROM (
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTGARBILL AA,GTGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTGARBILLID=BB.GTGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
UNION ALL
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTSECGARBILL AA,GTSECGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTSECGARBILLID=BB.GTSECGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
) BB WHERE BB.ORDERNO=D.ORDERNO AND BB.PROCESSNAME=E.PROCESSNAME AND BB.STYLEITEM=F.STYLEITEM AND BB.COMBONAME=G.COMBONAME AND BB.COLORNAME=H.COLORNAME
AND BB.SIZENAME=I.SIZENAME AND BB.DETAILID=C.GTGINPRODSUBDETID),0) ELSE NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.ORDERNO AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME=E.PROCESSNAME AND EE.COLORNAME=H.COLORNAME
),0) END ARATE,
CASE WHEN J.COMPNAME IN ('ANUGRAHA FASHION MILL PRIVATE LIMITED','FREELOOK FASHIONS','VELAV GARMENTS INDIA PRIVATE LIMITED') THEN C.DAILYPROD*
NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2)
FROM (
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTGARBILL AA,GTGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTGARBILLID=BB.GTGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
UNION ALL
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTSECGARBILL AA,GTSECGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTSECGARBILLID=BB.GTSECGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
) BB WHERE BB.ORDERNO=D.ORDERNO AND BB.PROCESSNAME=E.PROCESSNAME AND BB.STYLEITEM=F.STYLEITEM AND BB.COMBONAME=G.COMBONAME AND BB.COLORNAME=H.COLORNAME
AND BB.SIZENAME=I.SIZENAME AND BB.DETAILID=C.GTGINPRODSUBDETID),0)
ELSE C.DAILYPROD*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.ORDERNO AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME=E.PROCESSNAME AND EE.COLORNAME=H.COLORNAME),0) END AAMOUNT
FROM GTGINPROD A,GTGINPRODDET B,GTGINPRODSUBDET C,GTNORDERENTRY D,GTPROCESSMAST E,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST J
WHERE A.GTGINPRODID=B.GTGINPRODID AND A.GTGINPRODID=C.GTGINPRODID AND B.GTGINPRODID=C.GTGINPRODID
AND B.GTGINPRODDETID=C.GTGINPRODDETID AND B.ORDERNO=D.ORDERNO AND A.DEPARTMENT=E.GTPROCESSMASTID
AND B.STYLEITEM=F.GTSTYLEITEMMASTID AND C.COMBO=G.GTCOMBOMASTID AND C.COLOR1=H.GTCOLORMASTID
AND C.SIZES=I.SIZENAME AND A.COMPCODE=J.GTCOMPMASTID AND D.ORDERNO=:ORDERNO
UNION ALL
SELECT A.ORDERNO,E.PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.RECQTY AQTY,(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTOPPBILLENT AA,GTOPPBILLENTDET BB WHERE AA.GTOPPBILLENTID=BB.GTOPPBILLENTID AND BB.COLOR=B.COLOR AND BB.COMBO=B.COMBO
AND BB.SIZES=B.SIZES AND BB.ORDERNO=A.ORDERNO AND AA.PROCESSNAME=C.PROCESSNAME AND BB.ORDERNO=:ORDERNO) ARATE,B.RECQTY*
(SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2) FROM GTOPPBILLENT AA,GTOPPBILLENTDET BB WHERE AA.GTOPPBILLENTID=BB.GTOPPBILLENTID AND BB.COLOR=B.COLOR AND BB.COMBO=B.COMBO
AND BB.SIZES=B.SIZES AND BB.ORDERNO=A.ORDERNO AND AA.PROCESSNAME=C.PROCESSNAME AND BB.ORDERNO=:ORDERNO) AAMOUNT
FROM GTOPPRECEIPT A,GTOPPRECEIPTDET B,GTOPPRECEIPTPRO C,GTNORDERENTRY D,GTPROCESSMAST E,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I
WHERE A.GTOPPRECEIPTID=B.GTOPPRECEIPTID AND A.GTOPPRECEIPTID=C.GTOPPRECEIPTID AND B.GTOPPRECEIPTID=C.GTOPPRECEIPTID
AND B.GTOPPRECEIPTDETID=C.GTOPPRECEIPTDETID AND A.ORDERNO=D.ORDERNO AND C.PROCESSNAME=E.GTPROCESSMASTID
AND A.ITEM=F.GTSTYLEITEMMASTID AND B.COMBO=G.GTCOMBOMASTID AND B.COLOR=H.GTCOLORMASTID
AND B.SIZES=I.GTSIZEMASTID AND D.ORDERNO=:ORDERNO
AND E.PROCESSNAME NOT IN ('ALL OVER EMBROIDERY','EMBOSSED PRINTING','EMBROIDERY','FOIL PRINTING','CHEST PRINTING',
'GLITTER PRINTING','HAND EMBROIDERY','PORTION PRINTING','PORTION PRINTING I','ROLL EMBROIDERY','SEQUENCE EMBROIDERY','SUBLIMATION PRINTING','YOKE PRINTING')
UNION ALL
SELECT B.ORDERNO,E.PROCESSNAME,SUBSTR(A.TRANSTYPE,1,3) TRANSTYPE,F.STYLEITEM,G.COMBONAME COMBO,H.COLORNAME COLOR,I.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,C.DAILYPROD AQTY,
CASE WHEN K.COMPNAME IN ('ANUGRAHA FASHION MILL PRIVATE LIMITED','FREELOOK FASHIONS','VELAV GARMENTS INDIA PRIVATE LIMITED')
THEN NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2)
FROM (
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTGARBILL AA,GTGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTGARBILLID=BB.GTGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
UNION ALL
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTSECGARBILL AA,GTSECGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTSECGARBILLID=BB.GTSECGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
) BB WHERE BB.ORDERNO=D.ORDERNO AND BB.PROCESSNAME=E.PROCESSNAME AND BB.STYLEITEM=F.STYLEITEM AND BB.COMBONAME=G.COMBONAME AND BB.COLORNAME=H.COLORNAME
AND BB.SIZENAME=I.SIZENAME AND BB.DETAILID=C.GTGINUPPRODSUBDETID),0) ELSE
NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.ORDERNO AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME=E.PROCESSNAME AND EE.COLORNAME=H.COLORNAME),0) END ARATE,
CASE WHEN K.COMPNAME IN ('ANUGRAHA FASHION MILL PRIVATE LIMITED','FREELOOK FASHIONS','VELAV GARMENTS INDIA PRIVATE LIMITED')
THEN C.DAILYPROD*NVL((SELECT ROUND(SUM(BB.AMOUNT)/SUM(BB.BILLQTY),2)
FROM (
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTGARBILL AA,GTGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTGARBILLID=BB.GTGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
UNION ALL
SELECT DD.ORDERNO,AA.EMPNAME,EE.PROCESSNAME,FF.STYLEITEM,GG.COMBONAME,HH.COLORNAME,II.SIZENAME,BB.AMOUNT,BB.BILLQTY,BB.DETAILID
FROM GTSECGARBILL AA,GTSECGARBILLDET BB,GTNORDERENTRY DD,GTPROCESSMAST EE,GTSTYLEITEMMAST FF,GTCOMBOMAST GG,
GTCOLORMAST HH,GTSIZEMAST II
WHERE AA.GTSECGARBILLID=BB.GTSECGARBILLID AND BB.ORDERNO1=DD.ORDERNO AND BB.PROCESSNAME=EE.PROCESSNAME
AND BB.ITEM=FF.GTSTYLEITEMMASTID AND BB.COMBO=GG.GTCOMBOMASTID AND BB.GARCOLOR=HH.GTCOLORMASTID
AND BB.SIZES=II.SIZENAME AND DD.ORDERNO=:ORDERNO
) BB WHERE BB.ORDERNO=D.ORDERNO AND BB.PROCESSNAME=E.PROCESSNAME AND BB.STYLEITEM=F.STYLEITEM AND BB.COMBONAME=G.COMBONAME AND BB.COLORNAME=H.COLORNAME
AND BB.SIZENAME=I.SIZENAME AND BB.DETAILID=C.GTGINUPPRODSUBDETID ),0) ELSE
C.DAILYPROD*NVL((SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.ORDERNO AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND CC.ORDERNO=D.ORDERNO AND DD.PROCESSNAME=E.PROCESSNAME AND EE.COLORNAME=H.COLORNAME),0) END AAMOUNT
FROM GTGINUPPROD A,GTGINUPPRODDET B,GTGINUPPRODSUBDET C,GTNORDERENTRY D,GTPROCESSMAST E,GTSTYLEITEMMAST F,GTCOMBOMAST G,
GTCOLORMAST H,GTSIZEMAST I,GTCOMPMAST K
WHERE A.GTGINUPPRODID=B.GTGINUPPRODID AND A.GTGINUPPRODID=C.GTGINUPPRODID AND B.GTGINUPPRODID=C.GTGINUPPRODID
AND B.GTGINUPPRODDETID=C.GTGINUPPRODDETID AND B.ORDERNO=D.ORDERNO AND D.ORDERNO=:ORDERNO
AND B.DEPARTMENT=E.GTPROCESSMASTID AND B.STYLEITEM=F.GTSTYLEITEMMASTID
AND C.COMBO=G.GTCOMBOMASTID AND B.COLOR=H.GTCOLORMASTID
AND C.SIZES=I.SIZENAME  AND A.COMPCODE=K.GTCOMPMASTID
UNION ALL
SELECT C.ORDERNO,D.PROCESSNAME,SUBSTR('PLANNING',1,3) TRANSTYPE,E.STYLEITEM,H. COMBONAME COMBO,F.COLORNAME COLOR,G.SIZENAME,'PIECES' UOM,
0 PQTY,0 PRATE,0 PAMOUNT,B.CREQQTY AQTY,NVL((
SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND DD.PROCESSNAME='OTHER COST'
),0) ARATE,B.CREQQTY*NVL((
SELECT AVG(BB.RATE)
FROM GTCMTRATEENTRY AA,GTCMTRATEENTRYDET BB,GTNORDERENTRY CC,GTPROCESSMAST DD,GTCOLORMAST EE
WHERE AA.GTCMTRATEENTRYID=BB.GTCMTRATEENTRYID AND AA.ORDERNO=CC.GTNORDERENTRYID AND BB.PROCESSNAME=DD.GTPROCESSMASTID
AND BB.COLORNAME=EE.GTCOLORMASTID
AND CC.ORDERNO=:ORDERNO AND DD.PROCESSNAME='OTHER COST'
),0) AAMOUNT
FROM GTBM A,GTBMCMTDET B,GTNORDERENTRY C,GTPROCESSMAST D,GTSTYLEITEMMAST E,GTCOLORMAST F,GTSIZEMAST G,GTCOMBOMAST H
WHERE A.GTBMID=B.GTBMID AND A.ORDERNO=C.GTNORDERENTRYID AND B.CPROCESSNAME=D.GTPROCESSMASTID
AND B.ITEM=E.STYLEITEM AND B.CCOLOR=F.COLORNAME AND B.CSIZES=G.SIZENAME AND B.CCOMBO=H.COMBONAME
AND C.ORDERNO=:ORDERNO AND D.PROCESSNAME='OTHER COST'
) GROUP BY PROCESSNAME,TRANSTYPE,STYLEITEM,COMBO,COLOR,UOM,ORDERNO
) X
LEFT JOIN
(SELECT C.PROCESSNAME,B.SEQNO FROM GTPROGROUPMAST A,GTPROGRPDETAIL B,GTPROCESSMAST C
WHERE A.GTPROGROUPMASTID=B.GTPROGROUPMASTID AND B.PROCESSNAME=C.GTPROCESSMASTID ) Y
ON X.PROCESSNAME=Y.PROCESSNAME
ORDER BY Y.SEQNO`,
    fields: [
      "orderNo",
      "processName",
      "description",
      "uom",
      "pQty",
      "pRate",
      "pAmount",
      "aQty",
      "aRate",
      "aAmount",
    ],
  },
};

// ---------------------------------------------------------------------------
// Single consolidated handler
// ---------------------------------------------------------------------------
export async function getOrderReport(req, res) {
  const { orderNo, reportType } = req.query;

  const report = REPORTS[reportType];
  if (!report) {
    return res.status(400).json({
      error: `Invalid reportType. Valid values: ${Object.keys(REPORTS).join(", ")}`,
    });
  }

  let connection;

  try {
    connection = await getConnection();

    const result = await connection.execute(report.sql, {
      ORDERNO: orderNo,
    });

    const resp = mapRows(result.rows, report.fields);

    return res.json({
      statusCode: 0,
      data: resp,
    });
  } catch (err) {
    console.error(`Error retrieving ${reportType} data:`, err);

    return res.status(500).json({
      error: "Internal Server Error",
    });
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (e) {
        console.error("Error closing connection:", e);
      }
    }
  }
}
